### ISSUE TITLE
After Updated, the Indivisible still CRC Error. 

### ISSUE THREAD

**Issue by tomgates** [MachineGunnur/GOG-Games#103]
After I posted Issue and Indivisible Updated, the Indivisible 03 and 11 rar file still are CRC Error. 
I try not to use "the copy links to clipboard button,"  which mentioned in :
https://github.com/MachineGunnur/GOG-Games/issues/99
but still CRC error in 03 and 11 rar file.
(I played this game already by IGG game, But I like here and love this place. I wish this place is ok )
(BTW, after playing this game. all I want to say is " this game is suck")

**Comment by MachineGunnur** [comment]
both hoster links are interchangeable. download the errored files from Zippyshare. use VPN or proxy to access if blocked.

**Comment by MachineGunnur** [comment]
I just download game from usersclouds and dl.free - no errors.... you're doing something wrong.

**Comment by mjr-ghost** [comment]
Downloaded too, 3 times, on VPS with ECC RAM and 1 Gbps Connection, have no errors whatsoever. What the OS, Browser, Drive Storage are you using, all Genuine? I'm not using a browser or JDownloader for, only Linux on default repos. No idea what have caused your issue, can only recommend, as usual, since don't know much nor saw your system, find it yourself:
1. Run MemTest86 to test RAM, can be compatibility issues or faulty;
2. Read Drive S.M.A.R.T. values, is your Reallocated Sector Count 0?
3. Verify System Integrity by running "sfc /scannow" in Windows CMD;
4. Send ping over the Network, if you've packet loss, blame the ISP;
5. Disable all browser extensions, especially ones who rewrite data;
6. Try to switch the browser to latest Firefox, Tor Browser, Chrome;
7. Hope not the case but check against Malware, those can do damage.

Go Zippyshare! The difference: GOG Games uploads directly but with Multiup what happens next, after its servers, including errors from time to time with some whom Multiup supports, technically not a GG issue. Thus Zippyshare stands for a good reason: Stability.

**Comment by tomgates** [comment]
@MachineGunnur  @ghost  thanks for your guys.
I still don't know what's the problem, but it's ok.
I will spend some time looking into it.
Anyway, thanks for your guys.

**Comment by MachineGunnur** [comment]
use download manager. jdownloader 2. error is completely on your end though, user only. files are intact
