### ISSUE TITLE
The site seems to be down

### ISSUE THREAD

**Issue by omrisim210** [MachineGunnur/GOG-Games#127]
I've tried both the onion.ws & onion.pet proxies and tor browser, all of them can't reach the site. I checked today and yesterday.
Is the site down? And is there an ETA for when it'll be back up?

**Comment by AntiKoshchey** [comment]
@MachineGunnur, WTF Dude, why closed the issue and even no comment?! Not to mention deleted my request ("Please Update Games") and a request to be humane to increase Donations. Well, no wonder why you're working solo then... Since the owner doesn't care about people and doesn't speak out about own issue, I need to interfere. Why is it MachineGunnur's issue? Coz Alternative on README.

@omrisim210, no, the site is not down. About a week or so I am expiriencing severe inability to connect from WS or PET Proxy sites, however, connecting directly really helps. Rarely getting timeouts even from a direct Tor connection. No idea what the Hell is happening. Technically a solution could be setting up a standalone GG Only proxy site (I could) but I don't want to do it.

So, mentioned PET and WS: For God's sake, @MachineGunnur, stop doing harm to yourself and at the very least suggest an HTTP solution for the person, your "client," someone who might even donate, eh. I knew how desperate you're for money, if you care about money, not people, at the very least serve your client and truely solve the issue. Closing an issue is not solving but ignorance!

I won't donate, ever, and do not recommend anyone for anything, better buy and share, dead simple. The fact is: MG never buys games, it is technically a leecher from P2P, sites like Tapochek and (sometimes) Torrminatorr or RIN: MG is like Russian Koshchey, has no team, no one likes to work with. I am from Russia too and I speak Russian natively, if brave enough, MG, speak RU.

**Comment by omrisim210** [comment]
Weird, I couldn't connect from Tor browser either.

The proxies seem to be working now though so I guess that's something

**Comment by omrisim210** [comment]
Seems like it isn't working again like I described here.
`https://goggamespc7v6z5e.onion.{ws,pet}` both show me the page for `https://onion.{ws,pet}` but with your site's URL in the address bar, while tor browser just keeps loading forever until it it shows a "connection timed out" screen.

@MachineGunnur do you have any idea why this is happening? Is it like this for everyone? Is it fixable?
