### ISSUE TITLE
Unable to request upload for some titles last updated over 1 month ago.

### ISSUE THREAD

**Issue by Kerian23** [MachineGunnur/GOG-Games#166]
There have been quite a few cases where a game may be older than 1 month and will not have a request re-upload button on the page. Nova Drift is one example. In this case the changelog says new versions are available and the search page says: "Last Update: 2 months ago." but there is no update button on the page.

Would you mind looking into this problem when you have time? :) Thanks!

Here are a few more examples that are more than 1 month old and do not have request re-upload buttons: Wizardry: Labyrinth of Lost Souls (3 months), Exanima (1 month), Dark Future (5 months). Death's Gambit does not say when it was last uploaded, and does not have an upload button either.

**Comment by MachineGunnur** [comment]
LAST UPDATE is not LAST UPLOAD date

**Comment by MachineGunnur** [comment]
https://github.com/MachineGunnur/GOG-Games/issues/11

**Comment by Kerian23** [comment]
I feel like there may have been a miscommunication on my part, let me try to clarify:
- The search page says Nova was "Last Updated 2 months ago." (This is not correct.)
- The patch notes page on Nova Drift says that the current version is: Update 0.27.20 (1 May 2020)
- The version for download has not changed since February: (setup_nova_drift_0.27.1_(36041).exe)

According to this site: https://www.gogdb.org/product/1728172699#builds
- 0.27.1   - 2020-02-10 <-- Current version on site, uploaded in February
- 0.27.12 - 2020-03-24 <-- Version that should be on site if last upload was 2020-04-28
- 0.27.20 - 2020-05-01 <-- Patch Note version.

If the game has been 'Updated' multiple times according to the patch notes since February, and was uploaded some time within the last month, it seems like the version on-site should have increased from version 27.1 to version 27.12 if it was last uploaded on 2020-04-28.
- The version on site is not the newest version. (Its over 3 months old)
- The search page says the game "Last Updated 2 months ago." when in reality it was last updated both ~14 days (v27.20) and ~50 days ago. (v27.12)

I hope that helps to clear things up a little bit!

**Comment by MachineGunnur** [comment]
dont own the game. none has shared the updated file(s).

**Comment by Kerian23** [comment]
Oh, well that would explain a lot of things. Thank you for clarifying.

**Comment by Anyfurry** [comment]
"Last Update is Last Upload" by Definition. Please look at [this issue](https://github.com/MachineGunnur/GOG-Games/issues/219), @Kerian23. We are many, three so far. The issue here is that literally everybody in the world who speak English thinks that an "update" means an "update," the word "update" itself actually mean this, the one should not have dropped "Files" after "Last Update" to not confuse folks. "Last Updated" is better to be "Updated Items:" Clear that "Items" mean only Game/Patch/Others, not links, the site is using "Items" for every game page to refer to files except for Goodies, using "Links" for Links, like, understandable from the context.
