### ISSUE TITLE
[Suggestion] Donation and Rating system

### ISSUE THREAD

**Issue by pythonInRelay** [MachineGunnur/GOG-Games#218]
Allow users to rate games and sort by rating so people know what to download. With an in place rating system available on the website, you will get a lot more users, and thus a lot more donations.

Also add a link to donate in the FAQ. I don't understand mentioning that you've had no donations in 5 months but the FAQ doesn't have a link to donate. I know it's at the top how much has been donated, but at least add some kind of explanation about where the money goes etc. As far as it is, the site is as bare as its gets and you need to give background and information if you want donations.

In any case, sorting by rating, even superfluous rating is the most popular form of sorting on any site and instantly shows whether or not a site has a good degree of users. I can't tell how many people use the site just by looking at it, therefore I don't know whether I should bother donating if it's not even popular etc.

I could go on longer but hey it's just my two cents.

**Comment by killerjerick** [comment]
Also no donation link on mobile, leaving this here as a reminder to donate when I get back to my pc.

**Comment by Anyfurry** [comment]
Agree on some of the two cents. Disagree on the others. Implementing a rating system would be tough. I am not sure if the reason is only the system. One of the reasons could be trust in general.

My main issue is the same as for you all. The owner is strangely complaining about no donations in 5 months while the FAQ has had no link to donate, no matter a browser or a platform. What is the total amount in dollars per year/month, how is it used, what will happen if not, what are the benefits for a donator? I do not trust it, I feel it can be closed at any time or by a bad turn of events like Good Old Downloads did. Money should go directly to the payment for the hosting of the two servers which GOG Games use, i.g. should be made clear by the hoster itself that GOG Games doesn't own a Bitcoin wallet.

On the topic of sorting: Probably better might be to "Borrow" (steal) ratings from GOG, sort both by the amount and GOG user's votes. No need to re-invent the wheel entirely when GOG already has the rest.

**Comment by MachineGunnur** [comment]
hi, you can click Donations to see how to donate.

what to download? just go to GOG.com and use their system, then come to the site as we have all games archived...

**Comment by MachineGunnur** [comment]
added link in FAQ.

**Comment by pythonInRelay** [comment]
> 
> 
> Agree on some of the two cents. Disagree on the others. Implementing a rating system would be tough. I am not sure if the reason is only the system. One of the reasons could be trust in general.
> 
> My main issue is the same as for you all. The owner is strangely complaining about no donations in 5 months while the FAQ has had no link to donate, no matter a browser or a platform. What is the total amount in dollars per year/month, how is it used, what will happen if not, what are the benefits for a donator? I do not trust it, I feel it can be closed at any time or by a bad turn of events like Good Old Downloads did. Money should go directly to the payment for the hosting of the two servers which GOG Games use, i.g. should be made clear by the hoster itself that GOG Games doesn't own a Bitcoin wallet.
> 
> On the topic of sorting: Probably better might be to "Borrow" (steal) ratings from GOG, sort both by the amount and GOG user's votes. No need to re-invent the wheel entirely when GOG already has the rest.

GoG rating is better than nothing but a lot of these old games don't work very well. If we had our own rating system it would work a lot better. People could rate the game based on things like compatibility and so on. As a barebones site for downloading GoG games it works well though.

**Comment by Anyfurry** [comment]
They don't work well, agree. Could be trouble on Windows 10; 8 is abounded and 7 is dead (EOL). I.g. GOG API is a demonstration that GOG is Heaven and Hell combined. Understand your idea, just afraid the system could be exploited unless GOG Games adds accounts who will be paid. Then if it will be exploited, at least for the profit of GOG Games. Would it work better, to had own? Depends on the implementation.

As you can see some repo issues from 2019 July 28 or 2020 January 11 were not done and probably never would be. Myself is very slow, months pass by in the blink of an eye. For the sake of kindness, the owner could add another "issue" with likely the same "nothing" outcome. Profits are unclear. If there was a cool chart or a study, showing the increase of donations due to implementing a feature, suspect it could be done already.

> added link in FAQ.

I see now. GOG Games should be fine for ~2 months, according to my observation if the math is right. ₿0.01112002 were received ($114.6) between 2020-09-04 19:33:39 and 2020-09-05 20:26:31. The per cent is clearly updated manually, right now 11% as it was when should be 19%. The claim of no donations for 5 months is deeply misleading today. Don't understand why the percentage is not automated. Nor I understand why not show "The Date of Death" instead of percents. Psychologically the date should be better in achieving the goal and can make red messages less needed.

Assuming the previous time made 111% and 100% represent a year: ( ₿0.07598162 - ₿0.01112002 ) / 111% = ₿0.00058433874 ($6.02, 1%), ₿0.00058433874 * 100% = ₿0.058433874 ($602.18, 100%), ₿0.058433874 / 12 Months = ₿0.0048694895 ($50.18). For example, a Storage Box wants $50 per month for a 10 TB storage and gives a lot of Traffic for, not bad. In total 16 months of activity were paid ($783.02) from 2019-07, secured until 2020-11 by some estimations.

Wish I could afford additional $50 per month. Will see today/yesterday if can figure out (if not, I'll edit the message). Kind of need 10 TB with 1 Gbps: Tricky to buy HDDs for my RAID-5 and the home ISP is a costly jerk. Still wondering how a combine approach can be implemented (of course Tor over VPN), and if it counts as a donation in a sense. The issue is we both have incompatible policy differences, it's a problem. For example, I put Quality first, not Speed, always run verification for ZIP, EXE and BIN, checksum (BLAKE2b, SHA-512 and SHA3-512) plus make AES-256 encrypted 1% PAR2 and sign the sum (RSA-4096 SHA-512 PGP).

> Each donation is used to help cover operating expenses (storage server, VPN tunnel and hosting). We DO NOT profit from donations.

Okay. Sounds fairly realistic, looking at the above. Please officially disclose rounded numbers for each and how much it costs per month. The numbers tell more than a claim of no profit and shall be helpful to calm down some skeptics. Not everyone wants to do the math to know what is visible. No secret that this thing costs no less than $50 per month, everybody, watching at the wallet carefully, knows this.

**Comment by Masamune3210** [comment]
From what I've seen of the last few months, no amount of abating some people will stop them from being annoyed enough to whine

**Comment by Anyfurry** [comment]
Yeah, the observation is correct: Red and CapsLock is screamy. Goes like that for years. Wish they could be chill. On the bright side I figured out that can afford 2 VPS and a storage server, will see how it goes, if anything. The most inconvenient part would be trying to sync my current, my home upload speed is slow as Hell. Thankfully the difference between this and GOG Games is small (less than a hundred GB). I don't see how $50 can be a problem, this is the cost of 1 game per month, handleable.

**Comment by mequare** [comment]
What did you see?
