### ISSUE TITLE
no linux editions of games

### ISSUE THREAD

**Issue by edwardbas-pl** [MachineGunnur/GOG-Games#250]
Can you add section with games with linux version. i would like to game natively on linux wehner it's possible.

**Comment by MachineGunnur** [comment]
No.

**Comment by edwardbas-pl** [comment]
why?

**Comment by mozo78** [comment]
Because they are ignorant and don't care. There will never be Linux section.

**Comment by edwardbas-pl** [comment]
you got the exact point... sadly..

**Comment by MachineGunnur** [comment]
> Because they are ignorant and don't care. There will never be Linux section.

Instead of being nasty, how about you be thankful instead of spiteful. Have you asked the question yourself maybe, it would increase work, more to do, more costs? Windows is the most popular platform. Simple. Focus is here. Windows is already enough work. I don't need to do MAC and LINUX, sorry. 

Now please leave you child.

**Comment by mozo78** [comment]
You are helping monopoly and kiss Microsoft's ass. People like you are not needed in the world.
