### ISSUE TITLE
Announcement: Upcoming changes

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#251]
Please be aware of the following major changes that will take place in the next few weeks.

~~- The **.com** TLD will redirect you to **.ru** TLD. This will go in-effect on or before **December 1st**. If you try  to visit the root domain (i.e. gog-games.com) or any games links (i.e. https://gog-games.com/game/gog_game_go_here) you will be sent to gog-games.ru **Update:** If you try  to visit  any games links (i.e. https://gog-games.com/game/gog_game_go_here) you will be sent to https://gog-games.ru/game/gog_game_go_here. Cloudflare page rule will handle redirect properly.~~

### File Hosters
Since the storage server has been upgraded and now has more bandwidth **(thank you for your support donors, because of you this is possible)**, we plan on phasing out [MultiUp.org](https://multiup.org) and directly uploading to file hosting websites. 

We are in process of writing and testing scripts to upload directly.

**Completed and testing currently:**
**[Pixeldrain](https://pixeldrain.com/)** - Uploads 500MB parts just like Zippyshare
**[1fichier](https://1fichier.com/)** - Uploads game/goodies/patch in one RAR archive (so, 3 total if a game has all three). **Note:** 1fichier **allows one download per 1 hour at full speed** (you can bypass with a VPN). If you have good download speed & peering to their servers, they are fast for huge games. Looking at you Baldur's Gate III....
 
**In-progress:**
- **[Uptobox](https://uptobox.com/)** - Script to interact with API and upload written. Needs testing. 500MB parts.
~~- **[uploaded.net](https://uploaded.net/)** - Upload script written. Needs testing. 500MB parts.~~ **Update 2:** Made some progress on debugging what was wrong. Should be OK adding now. Will see.

That would bring us up to 5 file hosters. 

1. Zippyshare
2. Pixeldrain
3. 1fichier
4. Uptobox
5. ~~uploaded.net~~

Feel free to comment below with your suggestions, ideas or comments. **We are probably going to limit the total amount of file hosters to 5 since we still do have montly bandwidth limits.**

**A kind thank you for reading to the bottom and pat on back.**

**Comment by fable-cable** [comment]
Why RU, not ORG? In fact both The Pirate Bay and Rutracker use ORG, it is an appropriate and tested choice, it seems. Rutracker used to have RU but the Russian gov't and copyrighters made trouble, these have a tough stand on and can take a domain off, as well as in addition to block any access from our ISPs, in fact even Rutracker is blocked right now. To avoid RU is safer.

———

Чего RU, не ORG? По факту и The Pirate Bay, и Rutracker за ORG, и, думается - достойный и проверенный выбор. Ранее у Rutracker был RU, но госы и копирайтеры навели шороху - у них жесткая позиция, могут отключить домен, а также блокировать доступ на уровне интернет-провайдеров, как с Rutracker и есть. Все кроме RU будет годнее.

**Comment by SilentMRG** [comment]
I have a doubt...

I heard that last year (2019) Russia started testing its own internet, called "RuNet", and it looks like that internet will come into effect next year (2021) or 2022.

In short, this internet will disconnect Russia from all the "world standard" internet. I think you should already be aware of this subject, right?

Without further ado ... My question is: If this happens, what will the "gog-games.ru" site look like for non-Russians? Because if Russia becomes isolated with its own internet, we (non-Russians) will lose access to the site and any inherent Russian content.

Maybe my reasoning is wrong, or maybe there is another method of accessing all of that content, in case that "dark" future happens.

Just to be clear: The question is about the site, but, I extend it to all Russian content shared on the "standard" internet for all peoples.

**Comment by SilentMRG** [comment]
In my view fable-cable is correct! It is better to switch to .ORG than .RU, or leave it as ".COM".

I'm not an expert on the subject... Only I see that .RU will end up creating countless problems... And nobody likes problems, right?

**Comment by lagseeing** [comment]
What happened to LetsUpload ? I really enjoyed them but no new games are uploaded there

**Comment by MachineGunnur** [comment]
> In my view fable-cable is correct! It is better to switch to .ORG than .RU, or leave it as ".COM".

.com and .org are operated by USA companies. bad longterm.



> In short, this internet will disconnect Russia from all the "world standard" internet. I think you should already be aware of this subject, right?

Political non-sense to extreme. 

> What happened to LetsUpload ? I really enjoyed them but no new games are uploaded there

API server was always becoming full and creating errors. Tried to work with developers but are slow to do anything.

**Comment by SilentMRG** [comment]
> .com and .org are operated by USA companies. bad longterm.

Understand. Although in my ignorance I see no problem with ".org", given that many sites use it, including PirateBay.

> Political non-sense to extreme.

On the political issue of "RuNet", I just mentioned something that has been on the internet since 2019. Whether it is true and whether or not it will happen... I don't know that. On the other hand, you must consider that you will lose many donors if the site ends up being restricted to Russia.

**Comment by alexhowell2a** [comment]
i mean there is a .games gTLD you can use. also other gTLDs are .net .org and .com, as specified by SilentMRG
wouldn't be bad to access the website on the gog .games or gog-games .net

**Comment by fable-cable** [comment]
I should humbly notice that the site from whom GOG Games comes had used ".com" for more than [2 years](https://web.archive.org/web/20180121215652/https://goodolddownloads.com/enter) until its own end without any domain-related issues and it was doing not only GOG but Scene and Retro, more risks were at.

@SilentMRG is correct. I, as a native Russian, can [confirm](https://www.themoscowtimes.com/2019/12/24/russias-interent-ready-isolation-officials-say-after-partial-shutdown-a68728) ([RU](https://roskomsvoboda.org/43778/)) and it made me to illegally obtain a EU satellite receiver to not loose the connection in a long term. In fact, in the next year it will [block](https://meduza.io/en/feature/2020/09/22/russia-s-digital-development-ministry-wants-to-ban-the-latest-encryption-technologies-from-the-runet) ([RU](https://meduza.io/feature/2020/09/21/ministerstvo-tsifrovogo-razvitiya-hochet-zapretit-sovremennye-protokoly-shifrovaniya-v-runete-togda-roskomnadzoru-budet-prosche-blokirovat-sayty)) TLS 1.3 and ESNI, DNS over HTTPS or TLS, the same as China [does](https://www.privateinternetaccess.com/blog/china-expands-great-firewall-to-block-https-traffic-that-uses-tls-1-3-and-esni/). Do you really want to share all my troubles of no luck and no benefits?

Do you wish to spare your precious time snd money on trying to circumvent these always rising issues? GOG Games uses TLS 1.3, you choose, to have HTTPS or trouble.

> .com and .org are operated by USA companies. bad longterm.

The Pirate Bay uses ORG from May 2016, over 4 years and today, so, have no fear, ORG is safe, objectively. Piracy is not legal in Russia, after the introduction of new antipiracy laws in 2013 and particularly after 2015. RU is a essentially a property of the gov't and RIPN/RU TLD GG with some links to: Do it is as risky as to use US. Better to avoid these national domains.

I mind you once asked an account for Tapochek. What is the domain of? NET. I don't think the owners of one of the biggest Russian pirate sites are stupid people. Then, ORG is operated by Ethos Capital, in fact, a private company, not gov't-run, which is why The Pirate Bay is not down and operates for years, while Rutracker has its RU domain stolen ([RU](https://m.roem.ru/18-02-2010/123802/u-torrentsru-otobrali-domen-po-predstavleniyu-prokuratury/)) by.

> Political non-sense to extreme.

Welcome to Russia: Extreme Temperatures, Rough Solutions, the Hugest Size of Land, Insane Politicians who do what others would consider nonsense. This is why we, native Russians, primarly host sites in other countries and do not use RU: Need some peace and quiet. We don't like the so-call Mad Printer ("бешенный принтер") of "laws." We are very tired of that but we, the citizens, cannot do much againat that.

Our Roskomnadzor gov't agency does block millions of innocent IPs in an attempt to kill Telegram, everybody here knows. It'll do the isolation of the Russian Internet as well. The gov't feels itself very insecure, it'll do whatever it takes to have an illusion of control, even if nuts.

Wiseful to reactivate Onion (with ReCaptcha) if worry: Rutor and The Pirate Bay do. Using ORG, INFO, NET, etc is OK. Let's not put all eggs in one busket.

———
 
Не до переводов, и так длинно.

**Comment by SilentMRG** [comment]
I think the best would be ".org" or ".net".

The ".onion" takes a long time to open the pages and not everyone is comfortable with accessing the fearful (for many) "Deep Web", because it requires a specific browser that many do not want (for whatever reason).

There is another factor (related to .onion) that the site is "hidden", and with this, away, possible donors. The website should, in my humble opinion, be accessible to everyone from the standard internet.

Note: I'm not an expert on the subject and maybe I'm talking a lot of shit! Anyway, that's all I think.

**Comment by MachineGunnur** [comment]
Verisign also owns .net (US based)

**Comment by fable-cable** [comment]
Tapochek is nore than [a decade on NET](https://web.archive.org/web/20090410024833/https://www.tapochek.net/), no problems.
———
Тапочек более [десятка лет с NET](https://web.archive.org/web/20090410024833/https://www.tapochek.net/), и поживает норм.

**Comment by MachineGunnur** [comment]
OK probably just stay on .com then. Anyways, need some input on file hosters:

**Tested Uptbox some, results:**
1gigabit upload with API. great! No issues.

**Tested Uploaded.net some, results:**
Sporadic, files upload 100%, stalls for 30 seconds (usually) then get 504 error. Tested with online JS uploader they have and same results. File upload 100% and never outputs download link. Not using waste of bandwidth.

**Are there any other decent file hosters out there? Pref with API.**

**Comment by fable-cable** [comment]
Okay, then probably can help with API file hosters. I wrote [4 simple upload scripts](https://tinyurl.com/y3q94fn8) to save your time, it can load a file given in an amount of tries specified until success. It has: anonymousfiles.io, sql.gg, drop.cx and gofile.io. Please take a look if it works fine for GOG Games itself.

Usage:
`script -- [FILEs]`

———

Вот и ладненько, смогу помочь с API хостерами тогда. Написаны [4 скриптика для загрузки](https://tinyurl.com/y3q94fn8), чтобы сэкономить ваше время - работают с выбранным числом попыток пока не получится. Имеется: anonymousfiles.io, sql.gg, drop.cx и gofile.io. Пожалуйста, взгляните, работает ли для нашего случая.

Команда:
`скрипт - [ФАЙЛы]`

**Comment by Reis963** [comment]
[Megaup](https://megaup.net/) ?

**Comment by cupelix1** [comment]
Is there a trick to downloading from Pixeldrain in Jdownloader 2? It says that it needs to verify captcha but does not open a window to do so.

Cupelix

**Comment by Sparoney** [comment]
Google Drive with [rclone](https://rclone.org/)?

**Comment by SilentMRG** [comment]
Google Drive has a serious problem with "Download/Transfer Quota" or whatever its name is.

I believe it would be better to leave just two hosters: ZippyShare and PixelDrain.

And then with little work to add a Torrent with seeders based on Bots, just like the old site GoodOldDownloads.

**Comment by MachineGunnur** [comment]
> Made an upload [script](https://pixeldrain.com/api/file/qKvubkLQ) ([Mirror](https://tinyurl.com/y5rnx7qx)). It can do: anonymousfiles.io, drop.cx, gofiile.io, sql.gg and etc. Please take a look if it works fine for GOG Games itself.

Thanks. Will test those sites.

> [Megaup](https://megaup.net/) ?

Will see.

> Is there a trick to downloading from Pixeldrain in Jdownloader 2? It says that it needs to verify captcha but does not open a window to do so.

Seems pixel drain has rate limiting now and will prompt captcha before download if file gets lots of downloads (tested in browser). Go ask jdownloader2 devs about this. Only ones can help.

> Is there a trick to downloading from Pixeldrain in Jdownloader 2? It says that it needs to verify captcha but does not open a window to do so.
> 
> Cupelix

> Google Drive with [rclone](https://rclone.org/)?

No won't be using Google. As SilentMRG said and you can't work around it now effectively with recent changes. Better off moving on. The good is in the past with this.

**Comment by MachineGunnur** [comment]
I am debugging uploaded.net  servers. Made some good progress. Notified Uploaded on their contact form but said was browser effecting... 

Anyways, I found more information what is happening and hope it helps them fix.

If you have knowledge in shell scripting can you please reach out at help_gg@protonmail.com  to help test?

Will provide shell script and information. Need to see if same results are experienced.

Thanks,

**Comment by fable-cable** [comment]
Stop using JDownloader for Pixeldrain, folks! The app dooms itself, see below.

PixelDrain will limit everybody and [said so](https://pixeldrain.com/api) quite honestly if a file is not viewed much, which is what your app  badly do. Take a look at Staxel: The first RAR, 7 views but 18 downloads. This isn't OK. When it will be 70, you will 100% have trouble. 

"The rate limit will be enabled if a file has ten times more downloads than views," "Rate limiting has been added to prevent the spread of viruses and to stop direct linking," PixelDrain.

I could run a bot to fix views, it isn't impossible but at the end of the day, it is the problem of JDownloader, not mine nor GOG Games'. I think a warning should be pinned on Github and notified on the site to avoid people shooting themselves in the foot by until the devs fix. 

———

 Короче, не используйте JDownloader на PixelDrain, программа не смотрит страницу файла и после 1 к 10 по загрузкам PixelDrain включит ад. Напишите разрабам, кто-нибудь, чтобы прежде чем загружать, на ".../u/${ID}" ходили - иначе боль.

**Comment by fable-cable** [comment]
I may probably take a look that.
———
Возможно взгляну от балды..

**Comment by MachineGunnur** [comment]
drop.cx - no jd2 support
gofiile.io - downloads dont work. constantly reconnects then jd2 stops for 30 minutes
sql.gg - uses cloudflare. large uploads fail as you have to chunk upload them
anonymousfiles.io - same as sql.gg
megaup.net - same as above need to chunk uploads

**Comment by fable-cable** [comment]
Unfortunate. Thanks for the feedback: I couldn't know how it behaves at the server location. At least tried something. I don't see much for now with API except these tried or present. Maybe other users can suggest something better.
———
Невезуха. Но спасибо за отзыв - не могу знать, как себя ведет на сервере. Попытка не пытка. Пока особо не вижу API, кроме тех, что пробовали или есть. Может другие смогут предложить что-нибудь получше сюда.

**Comment by MachineGunnur** [comment]
I have to look into doing chunked uploads to test megaup, etc. with cURL, never tried.

Here is uploaded.net test script: https://www47.zippyshare.com/v/Z943ljkt/file.html

Please read, change and test. Comments provide good guide.

**Comment by SilentMRG** [comment]
I still think that Torrent, with Bots (seeders) in place of human seeders, will be a good way! I just don't know how to do that, hehehe. I remember that on the old site it worked very well.

With that in mind, there would be no need for multiple hosters. Therefore, ZippyShare and PixelDrain would be sufficient.

Just my opinion. =)

**Comment by fable-cable** [comment]
Tested, the same. AM4 are absolutely OK, FRA ones are junk and stall for no reason. However, I read the script and instantly rewrote by my liking. The list of changes below.

- No dependencies except `curl`
- No temporary files
- Generates a new 8 MB test file in RAM
- More verbose on what's going on
- Variables are Lower Case 
- Picks any server but France

Download:
https://www36.zippyshare.com/v/dIr0xdPl/file.html

**Comment by TheMercenary333** [comment]
First of all, I like the design and overall functioning of your site very much. 
Can you change the voting process required to queue for games to reload with just one click? Because the confirmation process is not performed over a mobile phone. Also, the mobile version of the site does not show a queue. Can you fix it? On the other hand, in the past, when games received updates, update information was included. Any chance you can bring this back? 
Games on Zippyshare are separated into too many parts. But the download speed is very good. Ideal for small games. But in terms of oversized games, downloading is problematic. There are too many parts involved. First, do you have a chance to use encrypted Google Drive (such as [https://hermietkreeft.site/](url)) or OneDrive systems? Because the speed in these is fine. If not, I'll recommend other filehosters for your review.
•	CloudMail.Ru 
•	MediaFire
•	LetsUpload
•	Dropbox
•	Racaty.net
•	Yandex Disk
•	DepositFiles
•	WeTransfer 
•	BayFiles 
•	SugarSync 
•	Filefactory.com 
•	Keep2share 
+++ Also check on [https://alternative.app/zippyshare](url)

**Comment by fable-cable** [comment]
Putting in Queue and Queue itself is working fine on my ancient phone. The only issue is when I click a game page, it loads too slow for no good reason, only acceptable by opening in a new tab, else it takes minutes.

> No won't be using Google. 

Said this all. Will not happen and I fully agree with, I remember when was used, it was nothing but trouble, better without.

> Ideal for small games. But in terms of oversized games, downloading is problematic. 

Objection. Zippyshare is Perfecr for everything, even "Metro: Exodus," just use a download manager please or a [Bash script](https://github.com/ffluegel/zippyshare). It has proven itsel from the very early to these days as the most reliable while other hosters were changing like a kaleidoscope. There is absolutely nothing problematic, speeds are a bliss, not limited. 

> BayFiles

I will suggest only that from the list over Uploaded.net at any time, [it has API](https://bayfiles.com/docs/api), it looks. The site is 9 years old. The speeds to me were not amazingly great but surely better than snail speeds of Uploaded.net without an account. I think would be good to take a look.

**Comment by TheMercenary333** [comment]
Also, you can look at these ones.
* Smartfile.com
* Rapidgator
* Turbobit.net
* AWS S3
* Filefactory
* Uppit.com
* TusFiles
* Download.gg
* Oboom
* Multiup
* 4Shared

**Comment by fable-cable** [comment]
Please would you kindly not input all from the list but only these who may work for GOG Games?

**Comment by fable-cable** [comment]
Has API
- BayFiles

No API
- Racaty.net
- Uppit.com

Limited
- MediaFire - 200 MB filesizes
- Keep2Share - 2 GB per day
- DepositFiles - 5 GB per day
- WeTransfer - 7 days expiring
- TuisTransfer - 15 days expiring
- Rapidgator - 100 Kbps down speeds
- Oboom - 50 GB per account
- Dropbox - 2 GB per account
- 4Shared - 15 GB per account

Paid
- AWS S3
- SugarSync
- Filefactory.com
- Smartfile.com

Removed
- LetsUpload
- MultiUp
- Google Drive

Unfit
- Download.gg - Blocks VPN/Tor
- Yandex Disk - Russia
- Cloud Mail.ru - Russia

**Comment by MachineGunnur** [comment]
> First of all, I like the design and overall functioning of your site very much.
> Can you change the voting process required to queue for games to reload with just one click? Because the confirmation process is not performed over a mobile phone. Also, the mobile version of the site does not show a queue. Can you fix it? On the other hand, in the past, when games received updates, update information was included. Any chance you can bring this back?

Major site re-design is coming next year, so won't be putting any work into the site in current state as will be wasted. 



> Games on Zippyshare are separated into too many parts. But the download speed is very good. Ideal for small games. But in terms of oversized games, downloading is problematic. There are too many parts involved. First, do you have a chance to use encrypted Google Drive (such as https://hermietkreeft.site/) or OneDrive systems?

Use jdownloader2, solves any needs to click. Why make life harder when tools are out there to make easy :)?

No, Onedrive and Google drive are useless for sharing files en-mass as they will get rate limited and no way around. Google has patched the bypass of everyone was using.

**Chunked uploads are easy with cURL. Will be testing MegaUp.net uploads this week. Pixeldrain removed**

**Comment by fable-cable** [comment]
> Chunked uploads are easy with cURL

Is it done by `curl -XPOST -T @"${FILE}" https://example.com`, right? Still one slot left after the change. Wondering if the 5th will be chunked up anonymousfiles.io or sql.gg, or maybe BayFiles or slower to use uploaded.net.

**Comment by MachineGunnur** [comment]
> Is it done by `curl -XPOST -T @"${FILE}" https://example.com`, right?

Pass this as header: ```-H 'Tranfer-Encoding: chunked'``` then, cURL will handle on its own then.

I would like to keep uploaded.net. As some people do download from them, and it helps pay some bills too as collect some Euros form it (albeit very little). Helps.

BayFiles says:

**What are the limit of uploads?**

You are free to upload as long as you don't exceed the following restrictions:

    Max 20 GB per file
    Max 500 files or 50 GB per hour.
    Max 5,000 files or 100 GB per day.

If true, easily hit with how much we upload.

**Comment by fable-cable** [comment]
> Pass this header:

Okay, understand.

> BayFiles says:

Oh noes. Let's keep Uploaded.net then, especially since BayFiles seem to have unhandy limits per hour on upload, too small. I should have been more watchful and less briefly. There are already 3 good filesharing services, it should be fine. Not much other candidates left.

> it helps pay some bills

If it helps with pay, I support that. Be well.

**Comment by MachineGunnur** [comment]
Also, https://tusfiles.com is great to download from. Excellent speeds, no limits. Thanks for recommendation of it.

**Comment by fable-cable** [comment]
Strange. Its main page said 15 days but Upgrade said else: 7 for no account, no direct links, speed limits; A 1 TB limit per free account, 30 days, no direct, OK speed but limits the bandwidth; Paid has no expiration, all features but 1 TB too, small. And $15 for a TB is not cheap.

If can manage a dozen free accounts and divide games between, okay. If the uploder is Premium, speeds should be good.

**Comment by MachineGunnur** [comment]
Yes, I think will upload a file and wait and count. See which is true.

But I can create accounts, yes and have lots to randomly choose from and upload, too.

**Comment by MachineGunnur** [comment]
Probably will be able to add a 6th file hoster. Staying way under monthly bandwidth. If so, probably TusFiles.

**Comment by Reis963** [comment]
Thanks for add Megaup.

**Comment by TheMercenary333** [comment]
Could you check and review these filehosters? 
Uloz.to
Dropapk.net
File Dropper
Datafilehost.net
Files.com
SaberCatHost
ADrive
Filehosting.org
Seafile
Userscloud.com
DL.FREE.FR

**Comment by Reis963** [comment]
Suggesting all the file hosters on the internet does not help at all.

**Comment by fable-cable** [comment]
I agree, even a light imperfect review before suggesting would be helpful.

**Comment by fable-cable** [comment]
The owner already decided the 5, the 6th could be TusFiles. Not bad. I could first wait a month and see on traffic, no wish anyone to go beyond traffic limits. Let's maybe settle on the current and see how will go, play safe and no hurry, reliability and quality are the key.

**Comment by SilentMRG** [comment]
I requested the "Ziggurat" reupload, and it is only available on the "TusFiles" hoster. Error? Perhaps...

Right after that I requested the re-upload of "Pharaonic", and it is available in five hosters.

**Comment by fable-cable** [comment]
I see no error and everything as it should be now:
![Screenshot_2020-11-25-12-08-08](https://user-images.githubusercontent.com/73414640/100165581-82e47a00-2eb2-11eb-8d4f-5ed65348a177.jpg)

**Comment by fable-cable** [comment]
Maybe they were quickly testing something, no ideas.

**Comment by SilentMRG** [comment]
This is fact... There is no error and maybe it was a test. The it was my mistake!

I apologize!

**Comment by fable-cable** [comment]
No worry. Mistakes happen to everyone, you're fine.

**Comment by MachineGunnur** [comment]
Relax. Was testing TusFiles. 

Wrote script to upload with free accounts (selects a random one and uploads).

**Comment by cupelix1** [comment]
> 
> 
> Relax. Was testing TusFiles.
> 
> Wrote script to upload with free accounts (selects a random one and uploads).

I know this is not on topic, but MachineGunner is there feature or msg board to request file re-uploads? I am finding expired links on both Zippyshare and Multiupload for the game ELEX, usually your site features shows a request upload feature when links have expired right or automatically updates the files in new links? I am sorry this is off topic its just the only place I know to send feedback to the site admin right now.

Thanks

Cupelix1

**Comment by MachineGunnur** [comment]
> I am finding expired links on both Zippyshare and Multiupload for the game ELEX

Zippyshare links are all up. Are you in in country blocking zippyshare? If so, use VPN to bypass.

Game was upload on october 28th. Why there is no re-upload button. Has not been 30 days past.

**Comment by cupelix1** [comment]
Thanks so much for responding to my message that was off-topic. I am on a VPN but the file host is based in the united states. I will try connecting through another country and see if that fixes it. Right now if I click on copy to clipboard in Jdownloader I get a bunch of garbage links, and if I try a manual download it gives me a page that says "Forbidden". Never had problem with Zippyshare before, this will be a first.

Thanks again MachineGunner, and Respect!

Cupelix1

**Comment by MachineGunnur** [comment]
> PS - I was able to access zippyshare via VPN in another country...and links were still missing for rar files 23,24,36 so I downloaded from the MultiUp link the missing files and renamed them and uncompressed. Not sure if I did something wrong but just wanted to let you know.

They are all there. I just checked. Added all links in JD2 all loaded. Even manually checked. It's an issue on your end. 100% working.

**Comment by MachineGunnur** [comment]
**TusFiles enabled for future uploads**

**Comment by Sparoney** [comment]
> No won't be using Google. As SilentMRG said and you can't work around it now effectively with recent changes. Better off moving on. The good is in the past with this.

Yeah true it's annoying that the quota issue happens. I think out of all the ways to download from Google now the only way is to right-click the file and "Make a copy" providing you have storage. But yeah you're definitely right, it's now become too much of a hassle unfortunately.

**Comment by fable-cable** [comment]
I checked the Good Old Downloads site, it looks like GOG Games already uses most. LetsUpload or Google are crap, two else died. Guess in regards to hosters the best is already done.

**Comment by MachineGunnur** [comment]
https://nopy.to/ would be great addition, read site, very well managed. But invite only currently, sadly.

**Comment by MachineGunnur** [comment]
All new added file hosters are stable. I'm sure issues will crop up once in a while, but so far results are satisfactory. Closing.

**Comment by fazlul101** [comment]
any idea to add torrent?

**Comment by fable-cable** [comment]
I like the new hosters very much, especially MegaUp and a what you've done so far. The order is Good too. It was a bliss to work with you and talk to. Only please don't test on a live site like with the Error 521, confusing. Overall, new changes made the site better. Thank you.

**Comment by TheMercenary333** [comment]
Have you tested before this filehoster? 
https://uploadev.org/

**Comment by MachineGunnur** [comment]
> any idea to add torrent?

Yes, but why? It would increase costs per month, only people leech and not seed. 

What's wrong with using download manager and downloading? You will always have way to get game, unlike torrent: no seeds, no files.

**Comment by MachineGunnur** [comment]
**game/goodies/patch under 500MB will upload to LetsUpload & Pixeldrain**

**Comment by MachineGunnur** [comment]
Update

    Pixeldrain will now upload game, extra, and/or patch as one archive if 10GB or below. NOTE: Do not use JD2 with Pixeldrain. Why? A rate limit will be enabled if a file has ten times more downloads than views. When a file is rate limited the user will need to fill out a captcha in order to continue downloading the file.

    Added Gofile. Same as Pixeldrain above. NOTE: Works best with Internet Download Manager or equivalent. JDownloader2 connects and reconnects from testing. Avoid using JD2 with Gofile.

    LetsUpload will work same as Pixeldrain. 10GB or below.

**Comment by MachineGunnur** [comment]
Some interesting discoveries:

Uploading without API on LetsUpload results in this:

```[{"size":0,"type":"","name":"Max uploads reached.","error":"You have reached the maximum permitted uploads for today.","error_result_html":"<td class=\"cancel\"> <img src=\"https:\/\/letsupload.io\/themes\/mngez\/images\/red_error_small.png\" height=\"16\" width=\"16\" alt=\"error\"\/><\/td><td class=\"name\">Max uploads reached.<\/td><td class=\"error\" colspan=\"2\">Error: You have reached the maximum permitted uploads for today.<\/td>"}]sU```

LetsUpload API does not accept large files. 4GB fails. Messaged, said would fix, never happened.

**Comment by MachineGunnur** [comment]
**Update:**

**All Hosters** - Max amount try and upload a file is now 3. Was infinite. Stalled queue, not good. Since many hosters now have way to get a missing part if this happens.

**LetsUpload** - switched out guest upload to API upload with account. No limits on  uploads per day this way. Uploads 500MB parts now if game/good/patch is 10GB or under. API has limit on max file size can upload or get NGINX error.

**Gofile** - tested upload servers and filtered out the slow ones. Implemented a min speed limit. If falls under for 60 seconds. Quits. 

**Pixeldrain** - Disabled for now. Need  implement some more error handling.

**Comment by stringles** [comment]
Please can Zippyshare made 12 or infinite?

It was proven to be the most stable and should not be an issue. Was it, really? IIfit's unstable, then drop. The reasoning is I am trying to address the Cloudflare bug but having a very chaotic, all over the place unreliable lists is tough. It requires me literally to query all links, especially when the old mixes of RAR/files or only 1 hoster, which is painfully slow.

It can help to address a rare possibility if for some bizarre reason (i.g. a server ISP issue or another's) a part is missing from all, not impossible in an outrage like sometimes happen globally and can be used to know the correct total amount. Though smarter to
```
while ping -A -t 9 -- "${zippyshare}"; do
sleep 5
done
```
...if something odd. In any case, having Stability is smart. Don't you agree? It is at the 1st place for a good reason.

**Comment by stringles** [comment]
*A request*. Can be The Most Reliable Zippyshare made 12 or infinite, or (better) check if the amount of files on Zippyshare matches MegaUp and an attempt to reupload if either has not all?

*Cloudflare*. It'll make sure that to hunt a bug like Cloudflare's will be possible fast or any issues alike. Right now, old files mixed RAR/etc, it isn't straightforward. In fact Zippyshare is the only variable who is generally reliable for checking the amount if links and practically always present.

*3 isn't Ideal.* In theory the downside of your trio method is if a bad ISP middles with routes or a temporary outrage, many links may be not done right to all and will be no notice. The code below can account it for a short time:
```
safewait()
{
local count max
# Won't allow not numbers for waiting
max="${2//[^0-9]}"
# Won't allow no domain
case "${1//[^[:alnum:]\-]}" in
    "")
        printf -- '%s' "safewait: No WWW" 1>&2
        return 1
    ;;
esac
# Wait forever on zero
case "${max}" in
    0)
        max="none"
    ;;
esac
# Defaults to 5 minutes on incorrect/none
max="${max:-"300"}"
# It uses 5 second chunks
max=$(( max / 5 ))
# Check and wait if an error
while ! ping -A -t 3 -- "${2}"; do
    # Rise the count
    count=$(( count + 1 ))
    sleep 5
    # Stop if matches the max
    case "${count}" in
        "${max}")
             printf -- '%s' "safewait: ERROR" 
             return 1
        ;;
        esac
done
# If pass, all good
printf -- '%s' "safewait: OK" 
return 1
}
```
*Usage: safewait "${domain}" "${five_seconds_or_more}"*. The function will wait until a server is up for about 5 minutes (default) or if responds at least once out of 3 small maximum fast pings. Using "safewait 0" will make it wait indefinitely until the network is back.

*Avoid a no RAR accident.* In any case, having Stability is smart. Don't you agree? Zippyshare is at the 1st place for a good reason. You can use `[[` and `readarrays` to count every cloud group after uploading and see if the maximum at least on 1 group matches expected.

Otherwise could arise a situation where RAR isn't on any hoster: Unlikely but not fully impossible.

**Comment by MachineGunnur** [comment]
> _A request_. Can be The Most Reliable Zippyshare made 12 or infinite, or (better) check if the amount of files on Zippyshare matches MegaUp and an attempt to reupload if either has not all?

MegaUp is sporadic with their server speed. Parts of day it is slow as snails. Others are completely stable.

I can increase Zippyshare more, but never really had problem when their servers. Always fast and up. Constantly best.

I can't guarantee 100% will upload to each hoster. It would slow down queue if one has prolonged outage, best to move on. 

Most are hosted in different datacenter so if one happens to have bad outage, won't effect others really.

**Comment by MachineGunnur** [comment]
Zippy is basically infinite retry again now.

**Comment by stringles** [comment]
MegaUp is sporadic? Oh noes. Well, better to know the truth than a lie, thanks. Will notice to myself.

Don't load to each hoster 100%, really, it is not worth the effort. Judging from the above not all of them are troublefree. Actually having 1 mainline makes the less reliables not a threat at all.

If different datacentres, yes, you are right, absolutely.

This is smart to have per hoster. Good, the result is great. Thank you very much.

**Comment by MachineGunnur** [comment]
- Added Clicknupload.co for total archives 10GB total or under
- Pixeldrain reinstated for total archives 10GB total or under. Max try is one due to their server being full alot.
