### ISSUE TITLE
Support for torrents

### ISSUE THREAD

**Issue by MachineGunnur** [MachineGunnur/GOG-Games#260]
Looking into automated torrent creation and seeding in future. Have base line of what needed, just need to write code and test. 

**What will have?**
- Auto torrent creation and seeding for new and updated games going forward
- Magnet links on site

**When will implement?**
- Next year, 2021

**How you can help?**
- Will fund raise in future for seedbox before implementing. So save money for when time comes.
- Currently using ```aria2c -S name.torrent``` to parse info_hash for magnet. If you can write pure bash to do so instead, be guest :-).
- **Sample torrent**:  https://pixeldrain.com/u/ndSUSFDK (no one is seeding, don't try to 'download', just to show torrent structure/naming/files: gamefolder_windowsgog_internal_gog_version_number)

**Comment by SilentMRG** [comment]
Unfortunately I don't know anything about programming! If I understood I would help you.

However, I remember that on the old site the automated Torrent, through Bots, worked perfectly.

I intend to spread the idea to attract new donors. =D

Since I am poor and have nothing to donate at the moment. =/

**Comment by stringles** [comment]
What is the benefit, does it increase reliability, accessibility, what's the price?

The benefit is access to data. But the data available anyway. Even Blocked Zippyshare is no problem because you've such a nice amount of mirrors. Accessibility is not the benefit.

Reliability. We all know how unreliable this is. Tonnes of leeches and only a few seed if any. If no seeds, it's dead.

Accessibility. Requires to install a torrent app. In some countries like Germany doing torrents is illegal and you can be fined. A cloud is safer. Accessibility doesn't increase.

It said to cost hundreds of dollars. What is better, to do the thing of no benefit or to make the site work longer? I highly for make the site last longer, not shorter, so think everyone else.

I have a good idea. A compromise to make feel better everyone: You make torrent files or uploads; We load data from one of your existing clouds, unpack, get the torrent, check and share. This way you ger free P2P from people who are great and save money. What do you think?

This way will get the best from both and you don't need to loose previous resources.

**Comment by stringles** [comment]
Maybe no subfolders, I'm afraid people are too lazy to recreate, just all files in 1 folder, simplicity.

**Comment by MachineGunnur** [comment]
> Maybe no subfolders, I'm afraid people are too lazy to recreate, just all files in 1 folder, simplicity. Make a fake folder, then `ln` files and make the torrent: No copy times, no space wasted.

I have all initial code written. Process is fast. 2 minutes to create a torrent with 70GB of data. 

Yes using symlinks already. Agree - will exclude sub directories - good idea. 

The cost is low. 120-150 euros a year. If people really want torrents they will have to donate before do more and that will come after new site is pushed to support torrent magnet links next year. 

Have problem adding torrents, just people will just know costs will go up some.

Best way will still always be direct download as can always get. Seedbox will be cheap and limited space. Maybe seed for 1 month at max then remove. Depends on total space get from box. 1- 2 TB at most.

**Comment by stringles** [comment]
Fast? Impressive! It makes any hashes like CRC32 obsolete and meaningless. Since a torrent file is like a hash.

Good to hear on subdirs.

Well, you do you. If this is no biggie, I am happy to see it, thanks. It is like an additional option if the folks will donate more on a certain amount to express willingness if I read correctly, okay. Hope it can be dropped as easily if any issues too.

A moving seedbox? Cool. Yes. You know, usually big popular games take some traction, small are troubled. In my opinion good to move not only by date but when a certain amount of seeders, like 50+. This way can shrink itself more and save resources while providing less crazy poplar yet good games too.

**Comment by MachineGunnur** [comment]
> Fast? Impressive! It makes any hashes like CRC32 obsolete and meaningless. Since a torrent file is like a hash.

**mktorrent** is really fast when hashing files. better than all torrent clients, deluge, qb, tranmission, etc. give it a go.

I just want to give people options, listen to them, just need their help to bring it to light.

**Comment by stringles** [comment]
You know, I was kind of against but after looking how "Cyberpunk 2077" affected a cloud storage service like no thousands can in years, I'll say that the games like this shall be primarily P2P to not affect other users. Not a matter of an option, the matter of stability in my opinion.

Meanwhile, great that have many mirrors even without P2P, else a single service might not handle such a title, no matter how good its servers are. Diversity is the key.

**Comment by MachineGunnur** [comment]
Yes all these hosters buckled under this game. Hehehe.

Looking at 2 seedboxes: 1, SSD box with 20gbit NIC for initial burst seeding and storage box for longer term.

**Comment by stringles** [comment]
Is there any progress, hopefully?

**Comment by MachineGunnur** [comment]
torrent creating has been implemented into scripts, turned off, all that remains is to buy a seedboxes, test & setup, and turn on torrent functionally going forward for new and updated games.

one downside is if a game gets re-uploaded, torrent will be cleared with all hosters as can't choose what to clear. will change in future. 

will start a fund raiser soon to buy the boxes.

**Comment by MachineGunnur** [comment]
Closing. See: https://github.com/MachineGunnur/GOG-Games/issues/293
