### ISSUE TITLE
Hitman games missing wallpapers

### ISSUE THREAD

**Issue by Wasmachineman-NL** [MachineGunnur/GOG-Games#261]
I already own all Hitman games on Steam but I really would like to have the wallpapers, but there's a few issues:

Contracts only has 1920x1080 wallpapers and I require 1920x1200
Blood Money has no wallpapers at all
So does Absolution. (but we don't talk about Absolution :^) )

**Comment by MachineGunnur** [comment]
this is not issue.

only provide extras what is offered - or not - from GOG.com

**Comment by stringles** [comment]
Nothing is missing. MachineGunnur is correct and does the task of maintaining pretty well. Files shoule be official and from GOG.

There is a few cases when RAR instead of the official ZIP, I check by Connie's DAT, shall say. But overall is extremely well. If by wallpapers you mean these JPG files that GOG offers, I thought to write a script who can quickly gather pictures into a ZIP and get videos from GOG API links by `youtube-dl`. However, I found it relatively meaningless to do, it is always here. Instead running archiving via the Wayback Machine.
