### ISSUE TITLE
Site down? Error code: SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by CHRONiCiTY** [MachineGunnur/GOG-Games#270]
Hi,

The site seems to be down right now with the following message:

Secure Connection Failed
An error occurred during a connection to gog-games.com. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG

Been like this since yesterday.

**Comment by stringles** [comment]
[Objectively no](https://archive.today/Sb8DH). I make regular queries over Tor and VPN, nothing is down. I could make an issue myself if I noticed alike. The issue lies within one's ISP or somebody bad tries to middle along the way. Please use [Tor Browser](https://www.torproject.org/download/) as a solution, it should help. This is not a GOG Games or Cloudflare problem.
