### ISSUE TITLE
Dying Light corrupted bin

### ISSUE THREAD

**Issue by seeker0xff** [MachineGunnur/GOG-Games#275]
Rar archive is unpacking fine, no errors here.
But setup_dying_light_the_following__enhanced_edition_1.34.2_(64bit)_(43453)-7.bin is corrupted - first 786432000 bytes are zeroes.
Maybe it would be wise to check integrity of gog files before raring them?
There are win/linux commandline tools - like innoextract or innounp - to automate this task.

**Comment by MachineGunnur** [comment]
Good idea. Implemented extraction into workflow so this will stop any corrupt crap now. thanks

**Comment by MachineGunnur** [comment]
Game was updated again too... update later

**Comment by stringles** [comment]
It will not stop "corrupted crap" and I can show why. For example, this will show success on corrupted:
```
cp -a "setup_ion_fury_1.1_(41245).exe" "/tmp/setup_ion_fury_1.1_(41245).exe.test" 
prinft -- "%s\n" "1" >>  "/tmp/setup_ion_fury_1.1_(41245).exe.test"
innoextract -t --  "/tmp/setup_ion_fury_1.1_(41245).exe.test"
rm - f  "/tmp/setup_ion_fury_1.1_(41245).exe.test"
```
Why? Because it literally extracts data, not testing the whole thing, only some parts. It is totally incompatible with the way how Windows and GOG actually work. Windows will complain about above. Since it "tests" BINs the same way, it will not stop GOG Setups from complaining about corruption either.

Moreover, version 1.7 on Debian 10 rejects to even test, saying the InnoSetup version is unexpected. The truth of the matter is it will break while GOG moves on where in reality for the task of testing a setup version is absolutely irrelevant. Even worse, the app ignores 7Z, GZ, RAR, PNG, JPG and others.

I will say that objectively `innoextract` is a bad choice for our task.
