### ISSUE TITLE
DOUBT - Fallout, Fallout 2 and Fallout Tactics

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#289]
Are the versions on the site censored or uncensored?

I read somewhere that GOG offered installers who were censored and uncensored, and the installer received depended on the player's country.

Thank you for your attention!

**Comment by SilentMRG** [comment]
Taking advantage of the topic... I realized that there are three versions of Fallout, Fallout 2 and Fallout Tactics.

Fallout

Old version: https://www.gogdb.org/product/1#downloads

Current version: https://www.gogdb.org/product/1440148836#downloads

Fallout 2

Old version: https://www.gogdb.org/product/2#downloads

Current version: https://www.gogdb.org/product/1440151285#downloads

Fallout Tactics

Old version: https://www.gogdb.org/product/3#downloads

Current version: https://www.gogdb.org/product/1440152063#downloads

There is a difference in these versions! The size of the installers as well as the version. The "Classic" version has more goodies than this other version. However, I suspect that the current installer should come with some graphical improvement or whatever.

Anyway, this is not a request, I am just informing you.

Thanks for reading!

**Comment by rasay1** [comment]
Fallout Tactics is the same version, only Fallout and Fallout 2 are different versions

**Comment by SilentMRG** [comment]
Fallout Tactics Classic - Version N / A. Possibly an installer with a numbering (version), specific the GOG.

Fallout Tactics - Version 1.27 (gog-12). This is the latest installer and there may be some difference in the game files, like some graphic modification, maybe, for higher resolutions or something like that.

In summary, the site is offering the old installers for the three games.

**Comment by rasay1** [comment]
Just to clarify, Fallout Tactics - Version 1.27 (gog-12) = 2.1.0.12

There have never been a newer version available than 2.1.0.12 also noted as Version 1.27 (gog-12).

Fallout Tactics Classic - Version N/A = 2.1.0.12 (Some older games the version are not listed in gogdb)

**Comment by SilentMRG** [comment]
In any case, the installers the site were provided by Interplay Entertainment, while the current installers sold on GOG were modified and provided by Bethesda Softworks.

I don't remember where I read it... But these old Interplay Entertainment installers don't support DirectX9 or higher resolutions, and the possibly, they run via DOSBox. On the other hand, current installers (Bethesda Softworks) support DirectX9 and higher resolutions as well as run natively on Windows.

The GOG versions are currently the same versions as Steam. Interplay Entertainment versions have not been sold on GOG for years! And these are the versions that are on the gog-games website.

And in response to Fallout Tactics Classic or not Classic: The versions may be the same, but there are internal differences in the installers, and for obvious reasons.

Anyway, the site owner has not expressed interest in the information.

Thanks for reading!

**Comment by stringles** [comment]
As far as I see, only the UK and German versions are censored. In regards to these, I have messages that: "Fallout 1" [has](https://www.gog.com/forum/flatout_series/fallout_censored) some Censorship because GOG offers the UK version for whatever reason; "Fallout 2" [is](https://www.gog.com/forum/fallout_series/is_the_gog_version_of_fallout_2_censored) uncensored; "Fallout Tactics" [seems](https://www.gog.com/forum/fallout_series/is_fallout_tactics_uncut) to be uncut. That's about it.

**Comment by stringles** [comment]
If there will be data that the "new" installer differs and became uncensored, I think there should be made an issue for, it is important for the game being original after all. Otherwise I don't see much of a reason to do anything, really, I could closed the issue too. GOG Games is known for mostly doing only official stuff, though I do have a case when a Goodie ZIP file is definitely unofficially packed in RAR and I fixed that in my copy.

However, looking at my "setup_fallout_2.1.0.18" and the new being "1.02 (gog-18)," thus probably just I minor update of the installer with changing Goodies, I am not sure if GOG suddenly got out of the UK version, likely not. I just will download the unnofficial patch and drop in my folder, that's faster than investigate a game I am not really that much interested to play. I prefer others to play actually.

I could someday attempt to find the "new" installer and see with InnoExtract what files differ and if it is censored or not if I have time for that. But quite honestly, knowing my "speed," it may never happen. If it will happen and I'll find that the new is uncensored, I must create an issue then, otherwise nothing will be created. Better to know as is, even the bitter truth, than to know nothing in my opinion.

**Comment by SilentMRG** [comment]
For more information:

Fallout: https://www.pcgamingwiki.com/wiki/Fallout

Fallout 2: https://www.pcgamingwiki.com/wiki/Fallout_2

Fallout Tactics: https://www.pcgamingwiki.com/wiki/Fallout_Tactics:_Brotherhood_of_Steel

Well, these are the complementary information that I was able to find. The new installers have been with GOG since 2015. The installers on the gog-games website are the ones from before 2015.

As stated earlier: It is just for information.

Thanks for the answers!

**Comment by SilentMRG** [comment]
Taking advantage of this topic... Please, I have a question: What changes in the new Trine 2 installer? I have an installer here that is before this 2.01 build 447 that was updated on the website. It's just that I don't want to re-download the game if there are no significant changes. There is no changelog and from what I saw on gogdb this new installer is about 790 MB more than the previous installer.

**Comment by SilentMRG** [comment]
Again, taking advantage of the topic... There is a programmer who is doing an incredible job with a PS1 emulator: https://github.com/stenzek/duckstation

In a few months, the emulator has evolved to the point of leaving behind known emulators, like ePSXe and others.

Here is tip for those who do not know this fantastic project!
