### ISSUE TITLE
Stardew Valley Version

### ISSUE THREAD

**Issue by MasterXYZ5** [MachineGunnur/GOG-Games#290]
As you might know, the game Stardew Valley got recently updated with the 1.5 version. This version was updated on gog-games pretty quick, but recently a new patch (1.5.1) came out, and it's been almost 2 weeks already. I know that issues don't have to be created for out of date games, that's why I'm here only to ask you this: why is it taking so long to get the last patch, even if other sites (ovagames is an example) already uploaded the offline gog installer for it? Can't you just get it from them or from their source?

**Comment by SilentMRG** [comment]
The gog-games provides games officially compressed by GOG itself, that is, they are legitimate installers in all aspects.

On the other hand, ovagames and other similar sites, do not provide installers officially packaged by GOG, that is, there are technical differences in the installers of these sites compared to the installers gog-games.

It is due to the quality control gog-games that some releases and even updates take time to be released.

But you can help the site by contributing a donation. Quality has always been expensive and quality is the mission of its creators. Help to gog-games on their mission... Donate!

**Comment by MachineGunnur** [comment]
simple: must have missed it. 

updated
