### ISSUE TITLE
System Shock - Enhanced is corrupt

### ISSUE THREAD

**Issue by coreyemtp** [MachineGunnur/GOG-Games#303]
Downloaded the latest version from multiple sources (mega, 1fichier, zippy) and all are corrupt. The RAR is fine, extracts fine, but when trying to run the executable it states the setup is corrupt.

**Comment by SilentMRG** [comment]
Unfortunately, the installer for this game is corrupted and it is GOG's fault!

According to: https://www.gog.com/forum/system_shock_series/changelog

The only solutions are to use an earlier version of the installer or wait until GOG fixes it.

**Comment by coreyemtp** [comment]
Thanks for the update, good to know!

**Comment by MachineGunnur** [comment]
yes, and https://github.com/guental/sigchk did not catch this. 

fixed now as gog fixed

**Comment by stringles** [comment]
What a mess.

@coreyemtp Would you kindly tell at which step of the installation process the error occurs: Is it running the EXE before processing, Self-Check or actual installing? 

@MachineGunnur As said above, this is GOG's Fault. The script trusts verification data GOG provides but if GOG broke and then signed and checksummed corrupted data, what can be done and how shall I really implement that? If there is a way, I am listening.

The script takes the singature data from GOG to check EXE. If GOG somehow corrupted EXE before signing, it won't be catched. Then it takes lonely MD5 which Self-Checking uses and checks the BIN(s). If GOG put corrupted BINs, it will never catch that.

The only thing I could imagine is to use `innoextract` in addition because it actually extracts like a installer's latest phase. Is it worth? I don't know. It seems GOG eventually fixes own, not mine, bugs. The best solution in my opinion is to be up to date.

**Comment by MachineGunnur** [comment]
if gog messed up and released bad data, their fault not ours of course. they usually correct so rare moment. imo no need to change, but yes, they should check their stuff before releasing...
