### ISSUE TITLE
Stellar Tactics 0.572_(64bit)_(44568)-2.bin corrupted

### ISSUE THREAD

**Issue by yerwi** [MachineGunnur/GOG-Games#304]
game can't be installed

**Comment by MachineGunnur** [comment]
yes i see and verify game script was not catching if last bin was corrupt. will fix later. thanks

**Comment by stringles** [comment]
The script does catch. The game was present from 2020-05-22 to [2021-02-05](https://web.archive.org/web/20210205074328/https://gog-games.com/game/stellar_tactics). "Stellar Tactics" currently [cannot](https://archive.is/VkYdm) be found for an unkown reason, nothing to investigate or fix in the official version. I bare no responsibility for personal changes. The last BINs always do go checked and the game can be installed according to tests below which can be repeated with any game and made sure that the script never misses the last.

**Comment by stringles** [comment]
_This message will be deleted after a day or two._

The hash of the script matches the repo's:
`sha512sum  /usr/local/bin/sigchk`
c939d7b741b1922dd1fbd8c358d0ae1ddb8205e6536a2c9e1a2f90c1e6345ca253df5032a24c9438933591f0dee1e8d93e12515067a84924676a52528d1b5f59  /usr/local/bin/sigchk

Extact MD5 values, from their 1st to 4th and 1st to 2nd BINs:
```
tac -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe" 2>/dev/null | cat -e | grep -m 1 '#GOGCRCSTRING'
tac -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe" 2>/dev/null | cat -e | grep -m 1 '#GOGCRCSTRING'
```

bbfd7f1eb8ee261f812e569ceec0cd00
4d25412868e408cfd26af16457b3c2e3
2c060f4674dc6761dd71df8569757295
5a394f625a776b08a85e6197d8614fa1
04#GOGCRCSTRING

9b0b3b04d30570783808cbd0954e8f04
eb4843e4bc4216c43ad5c97117f14fa4
02#GOGCRCSTRING

Check the data, not damaged yet:
```
sigchk -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe"
sigchk -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe"
```
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020).exe: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-1.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-2.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-3.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-4.bin: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500).exe: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-1.bin: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-2.bin: OK

Check the data, damaged on purpose:
```
sed -i 's/1/2/g' -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020)-4.bin"
sed -i 's/1/2/g' -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500)-2.bin"
sigchk -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe"
sigchk -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe"
```
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020).exe: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-1.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-2.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-3.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-4.bin: FAILED
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500).exe: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-1.bin: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-2.bin: FAILED

Check the data, the last is removed:
```
rm -f -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020)-4.bin"
rm -f -- "/home/${USER}/Documents/aquanox_deep_descent/setup_stellar_tactics_0.502_(64bit)_(39500)-2.bin"
sigchk -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe"
sigchk -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe"
```
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020).exe: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-1.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-2.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-3.bin: OK
/home/reaxole/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-4.bin: FAILED open or read
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500).exe: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-1.bin: OK
/home/reaxole/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-2.bin: FAILED open or read

**Comment by stringles** [comment]
_This message will be deleted after a day or two._

What does manual extraction show? Replace the line 21,413 from "03" to "02:"
`sigchk -- /home/${USER}/Documents/toca_race_driver_3/setup_toca_3.exe`
setup_toca_3.exe: OK
setup_toca_3-1.bin: OK
setup_toca_3-2.bin: OK

This is the only probable reason on my mind. The script blindly assumes the line does not lie, it puts a lot of trust into GOG's hands. If the GOG line lies, then it'll not check since it means no MD5 sums and no data can be trusted. The amount of MD5 sums always matches the last number.

The hash of the script matches the repo's:
`sha512sum  /usr/local/bin/sigchk`
c939d7b741b1922dd1fbd8c358d0ae1ddb8205e6536a2c9e1a2f90c1e6345ca253df5032a24c9438933591f0dee1e8d93e12515067a84924676a52528d1b5f59  /usr/local/bin/sigchk

Extract MD5 values, from their 1st to 4th and 1st to 2nd BINs and any mismatch with the last number from GOG will raise an error and "FAILED open or read," this is why not possible to not check all files:
```
tac -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe" 2>/dev/null | cat -e | grep -m 1 '#GOGCRCSTRING'
tac -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe" 2>/dev/null | cat -e | grep -m 1 '#GOGCRCSTRING'
```

bbfd7f1eb8ee261f812e569ceec0cd00
4d25412868e408cfd26af16457b3c2e3
2c060f4674dc6761dd71df8569757295
5a394f625a776b08a85e6197d8614fa1
04#GOGCRCSTRING

9b0b3b04d30570783808cbd0954e8f04
eb4843e4bc4216c43ad5c97117f14fa4
02#GOGCRCSTRING

Check the data, not damaged yet:
```
sigchk -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe"
sigchk -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe"
```
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020).exe: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-1.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-2.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-3.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-4.bin: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500).exe: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-1.bin: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-2.bin: OK

Check the data, damaged on purpose:
```
sed -i 's/1/2/g' -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020)-4.bin"
sed -i 's/1/2/g' -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500)-2.bin"
sigchk -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe"
sigchk -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe"
```
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020).exe: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-1.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-2.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-3.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-4.bin: FAILED
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500).exe: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-1.bin: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-2.bin: FAILED

Check the data, the last is removed:
```
rm -f -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020)-4.bin"
rm -f -- "/home/${USER}/Documents/aquanox_deep_descent/setup_stellar_tactics_0.502_(64bit)_(39500)-2.bin"
sigchk -- "/home/${USER}/Documents/aquanox_deep_descent/setup_aquanox_deep_descent_1.0b_(42020).exe"
sigchk -- "/home/${USER}/Documents/stellar_tactics/setup_stellar_tactics_0.502_(64bit)_(39500).exe"
```
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020).exe: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-1.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-2.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-3.bin: OK
/home/${USER}/Documents/aquanox\_deep\_descent/setup\_aquanox\_deep\_descent\_1.0b\_(42020)-4.bin: FAILED open or read
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500).exe: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-1.bin: OK
/home/${USER}/Documents/stellar\_tactics/setup\_stellar\_tactics\_0.502\_(64bit)\_(39500)-2.bin: FAILED open or read

**Comment by stringles** [comment]
I see it's back. Well, good that works, whatever the unknown "fix" is, thanks anyway, even if not known: All that matter is integrity preservation. Keep on going.
