### ISSUE TITLE
Ancestors legacy page bug

### ISSUE THREAD

**Issue by Numberzero-afk** [MachineGunnur/GOG-Games#306]
the page for ancestors legacy is completely blank and show no info, the download links works fine but most of them have 2 copy of the same part with different links (Probably happen because of re-uploading).

**Comment by stringles** [comment]
I can [confirm](https://archive.is/gmj4G) this, including the links. It's clearly a bug. I'll quickly query all the pages and report if find more alike.

**Comment by stringles** [comment]
Well, only this one.

I hope that none were affected by the "double URL" bug and will be not. If a filelist goes hand in hand with it, all clear. The check on the presence of "\.exe<" took me 2 hours and I could miss, crawling 3,080 pages isn't instant. Unless fixed, it would pop up somewhere at any time anywhere.

**Comment by Numberzero-afk** [comment]
Thank you for checking all the pages.

About ''Double URL'', I see it happen before and I think its a reupload bug. Because as I remember when downloading a game some month ago I hit reupload and after the game finished reuploading it still show it was uploading in queue but the bot (or script) move on to upload other games. so my guess is the bot either forgot that game was finished uploading or got canceled and that way the old links were still there and not removed.

**Comment by stringles** [comment]
I see. Welcome! Not hard to check since Cloudflare is not in a nightmare mode: In my interest too, as a collector. Knowing more cases could possibly help to discover and fix the roots of the issue. Fortunately it's rare, not very widespread.

The old links "got fixed" is likely why I didn't notice until now. I agree, it looks like probably an error in their script. Well, you know, nothing prevents the owner to run a check and query a set page for the required amount of links and presence of at 1 or more EXE as a temporary measure at least: It can be done in Bash or in Python, whatever is preffered.

I simply hope the situation will be resolved soon.

**Comment by MachineGunnur** [comment]
clearfiles and send files didnt hit api probably during that time frame as site was down/non-responsive.

will be fix next reupload :)

**Comment by stringles** [comment]
Okay. Would be great if it was checking if a query passed: Usually API answers if a query succeeded or not, like Pixeldrain does. This will prevent these issues forever.

Good if you will fix, thanks!

**Comment by stringles** [comment]
8 days pass, currently not fixed.

**Comment by stringles** [comment]
Finally I've fixed by "Vote for Re-Upload."
