### ISSUE TITLE
eDonkey as a Self-Efficent Mirror

### ISSUE THREAD

**Issue by elephantor** [MachineGunnur/GOG-Games#319]
eDonkey is a decentralized sharing network. `rhash` can make ED2K, then one may find the exact files by. It cannot be ever taken down unlike HTTP; Closer to P2P but data on 1-by-1 basis. To work, needs fully nothing from you except  to calc not RAR packaged item data.

Usage:
```
rhash -r --ed2k-link -- "${PWD}"
```
An Example:
```
ed2k://|file|empty.txt|0|31d6cfe0d16ae931b73c59d7e0c089c0|h=3i42h3s6nnfq2msvx7xzkyayscx5qbyj|/
```

**Comment by liketa4169** [comment]
**4 Mirrors by 1 Magnet**
_DC++, eDonkey, Gnutella, Gnutella2_

To make:
```
rhash -r --printf='magnet:?xt=urn:tree:tiger:%{TTH}&xt=urn:ed2k:%{ed2k}&xt=urn:aich:%{AICH}&xt=urn:sha1:%{SHA1}&xt=urn:bitprint:%{SHA1}.%{TTH}&dn=%u&xl=%s\n' -- "${PWD}"
```
A result:
```
magnet:?xt=urn:tree:tiger:LWPNACQDBZRYXW3VHJVCJ64QBZNGHOHHHZWCLNQ&xt=urn:ed2k:31d6cfe0d16ae931b73c59d7e0c089c0&xt=urn:aich:3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ&xt=urn:sha1:DA39A3EE5E6B4B0D3255BFEF95601890AFD80709&xt=urn:bitprint:DA39A3EE5E6B4B0D3255BFEF95601890AFD80709.LWPNACQDBZRYXW3VHJVCJ64QBZNGHOHHHZWCLNQ&dn=empty.txt&xl=0
```

**Comment by MachineGunnur** [comment]
simple no

**Comment by liketa4169** [comment]
Simple: Idiotic.

**Comment by liketa4169** [comment]
Who will reject free mirrors? You again made a wrong decision, harming users. Why? Oh yes, because you cannot put your pity "Uploaded from gog-games.com" and no other reason. Egoism.

**Comment by Masamune3210** [comment]
Are you broken inside or do you just like ranting at people

**Comment by mozo78** [comment]
He's doing the same with Linux games. Rude, impolite and ignorant person.

**Comment by bunjoe** [comment]
I remember Linux, it will never be done and always made an excuse even when got more money with space. Instead of extending, pretty useless yet costly "Torrent" was done, whose uploads too often die and have no seeders. What good is from a dead mirror? None, only eats money.

@Masamune3210 Do you like the fact we got a no-real-explanation answer but just straight "no," do you like hearing many times of screaming, ranting, lying and begging on the site in red every year by MachineGunnur, do you like rejecting absolutely free and no effort 4 mirrors? I don't.

It is costling basically nothing and could've improved availibility, resistance to DMCA, reliability and integrity. Thus insane that it just got rejected right ahead, there is no worthy reason for and no excuse. If the real target of the site is to share games, the 4 mirrors must be calculated, always.

**Comment by Masamune3210** [comment]
I dont like the way that stuff is done sometimes, but I don't like people's incessant ranting and raving in the issues farrrr more. Its not the place for it and accomplishes nothing other than making noise. It ultimately comes down to this, if people don't like something to the point of ranting and trying to kick up a problem, freaking go somewhere else or do it yourself

**Comment by moketo** [comment]
@Masamune3210 Read [Issue 322](https://archive.is/AhKbS#issuecomment-830575472) and think again.

**Comment by Masamune3210** [comment]
Do you have proof?

**Comment by moketo** [comment]
The proof is on the surface:
1. Observe the sources and notice how GG gets after publication, not before;
2. Compare update timestamps on the others and GG, the latter is never first;
3. Secondly use Open Source [BTDigg](https://btdig.com/) and notice how it's always last, like, enter "1.0.3 46693;"
4. Rejection of "unbrandable" magnet links only confirms the Issue 322 words.

**Comment by aaronliu0130** [comment]
> The proof is on the surface:
> 
> 1. Observe the sources and notice how GG gets after publication, not before;
> 2. [Compare](https://archive.is/chuim#issuecomment-830633577) update timestamps on the others and GG, the latter is never first;
> 3. Secondly use Open Source [BTDigg](https://btdig.com/) and notice how it's always last, like, enter "1.0.3 46693;"
> 4. Rejection of "unbrandable" magnet links only confirms the Issue 322nd words.

Sorry but eh I don't really get what you mean. First of all my browser has some issues with cloudfare so I can't get any of your links. Why archive anyway if the site isn't down? I completely don't understand your proof  No. 3 bc where should I enter that totally random semantic version? If you need to link to a(n) issue/pull request from this repo, just type hashtag(#) followed by the issue/pull number. 

> Who will reject free mirrors? You again made a wrong decision, harming users. Why? Oh yes, because you cannot put your pity "Uploaded from gog-games.com" and no other reason. Egoism.

Uhh everyone has their own problems with different things for different reasons. Some people are afraid of taking the elevator. Elevator implementations are open source, so by not taking the elevator they admit in their own egoism. Right? Wrong. A dream for a whole world filled with free software is beautiful, but impossible. There is just so much un-free software that are way ahead of all their competitors. You can perfectly add the branding to that edd2000 link. He may just have not enough space for, say A TON of mirrors? 
Honestly you're just ranting since your suggestion got rejected. This issue section was never meant to be for feature suggestions. It was ever meant to be for issues.
