### ISSUE TITLE
Battle Axe

### ISSUE THREAD

**Issue by SilentMRG** [MachineGunnur/GOG-Games#322]
Hi...

This game has a 32 Bit installer. If you purchased it, you have access to this installer and, please, add it.

If this game was donated... The person who donated it probably has access to this installer.

See here: https://www.gogdb.org/product/1402891706#downloads

My operating system is 64 Bit, however, many users still use 32 Bit systems.

This is not a request, it is just an alert for an item (patch/installer) included in the game that was left out.

Thanks for listening! :-)

**Comment by Metalschlumpf** [comment]
MachineGunnur and buying games... that's a good one! The truth is he steals 99,9% of the games to run this website. These are his sources:

**Tapochek.net** (Svyatovlad21 aka Leader RG GOGFAN), **forum.torrminatorr.com** (JohnnyMic, sammuggelton, Dreamer1971, Nighted, Shaka & Piepmatz), **RuTracker.org** (InsaneRamZes, Mart1z & olek2010 aka nelex) and in rare cases **Razor1911** scene releases.

He take them minutes after posting (without leaving a "Thanks" of course), rebrand them with his "gog-games.com" messages and tries to raise money here with the games. He's a thief, fraud and a lying asshole. Many contributors (including me) stopped buying & sharing new games because of him! If the 10 people above stop buying & sharing games on this sources in the future... that's it! No more GOG Games for all of us!

So go ahead... give him your hard earned money but don't blame any other than yourself when there's no new GOG Games in the future!!!

**Comment by moketo** [comment]
In my opinion, MachineGunnur shall:
* Stop begging in red for donations like crazy;
* Admit that GG is "secondhand;"
* Remove "branding" forever;
* Use "thank" button or say so;
* Always transfer most money to the 10;
* Support and holy those people like nobody else;
* Always credit a contributor explicitly on a page;
* Put a direct pirate source link of taken stuff;
* Calculate DC++/ED2K/Gnutella2 magnet URLs;
* Have a XMPP or Matrix chat for feedback.

**Comment by moketo** [comment]
The above changes may bring the 32-bit installer, fix the root issue and help us all, hopefully.

"Do not create issues for out-of-date or missing games/DLC" exists since practically MachineGunnur never buys games and cannot solve it. As such, I looked the entire Clearnet and DHT swarms, nobody shared yet: Unless somebody does, Issue 322 won't be solved, ever.

**Comment by Metalschlumpf** [comment]
For those who don't believe me. Here are the last 4 pages of GOG Games from RG GOGFAN on Tapochek.net (registration is open only in summer):

https://i.imgur.com/8ycaG8g.png
https://i.imgur.com/0dMXmkD.png
https://i.imgur.com/nXoesqi.png
https://i.imgur.com/8uFOpbI.png

Registration on Torrminatorr is always open: https://forum.torrminatorr.com/viewforum.php?f=13

**Comment by moketo** [comment]
Direct links to the images for NoScript users:
[Screenshot 1](https://i.imgur.com/8ycaG8g_d.webp?maxwidth=1920&shape=thumb&fidelity=medium)
[Screenshot 2](https://i.imgur.com/0dMXmkD_d.webp?maxwidth=1920&shape=thumb&fidelity=medium)
[Screenshot 3](https://i.imgur.com/nXoesqi_d.webp?maxwidth=1920&shape=thumb&fidelity=medium)
[Screenshot 4](https://i.imgur.com/8uFOpbI_d.webp?maxwidth=1920&shape=thumb&fidelity=medium)

**Comment by Metalschlumpf** [comment]
Now all new games & updates for the past week are online on Tapochek and Torrminatorr. New games provided by:

**Dreamer1971**/Torrminatorr: Port Royale 3 - Gold Edition & Patrizier 4 - Gold Edition

**Everard**/Torrminatorr: The First Templar - Special Edition, Imperium Romanum - Gold Edition & Demonicon

**Svyatovlad21 aka Leader RG GOGFAN**/Tapochek.net: Battle Axe, PC Building Simulator - EVGA Workshop DLC, Steel Division 2 - Burning Baltics DLC & R-Type Final 2 - Digital Deluxe Edition

**sammuggelton**/Torrminatorr: The 7th Circle - Endless Nightmare, Inferno - Beyond the 7th Circle, Speed Limit, Super Chopper & Super Huey™ 1 & 2 Airdrop

**Piepmatz**/Torrminatorr: Port Royale 4 - Extended Edition

All game updates provided by **Svyatovlad21 aka Leader RG GOGFAN**, **JohnnyMic**, **sammuggelton**, **Nighted**, **Shaka**, **Yasha** & **InsaneRamZes**!

**This should be pinned on the Frontpage right under his red banner where this Asshole ask for money "to buy new and missing games"!!!**



Have a nice day!

**Comment by SilentMRG** [comment]
A partnership between these sites / forums will be a good deal for everyone! We must be a single flag. Let's drop our weapons.
