### ISSUE TITLE
.

### ISSUE THREAD

**Issue by asqwedd** [MachineGunnur/GOG-Games#332]
.

**Comment by genedir** [comment]
Hello, I am a collector too

I think I can 100% help you with.

I will contact you under the "krschhhhh" name alias on RIN. I love the idea and it'll benefit us both because my target is to have it offline too and if something happen we will be able to potentially recover from each other. I have 1 Gbps, 10 TB SSD RAID, 20 TB of Traffic per month.

On the subject, yes API was planned but never is done, let's not expect that and adapt.

**Comment by genedir** [comment]
I suggest to delete this issue,seriously
