### ISSUE TITLE
Hitman Blood Money crashes after first mission

### ISSUE THREAD

**Issue by Kronifer** [MachineGunnur/GOG-Games#362]
This was broken by the v1.2 hotfix, if it is possible I suggest replacing the download with the old 1.0 version.

**Comment by Fireviewer** [comment]
https://www.gog.com/forum/hitman_series/hitman_blood_money_crashing_after_intro_level 
https://steamcommunity.com/app/6860/discussions/0/3201496051820157651/

The setup gives a broken product, I can say the issue does exist, widely. 1.0 doesn't exist, incorrect.

GOGdb shows only 1.2 Hotfix and just 1.2. Because the crashing reports appear exclusively after the hotfix and people blame that, it makes sense rolling back to 1.2 existing for a year before and wait.
