### ISSUE TITLE
You are a Public Servant, Get Over It

### ISSUE THREAD

**Issue by undeadlet** [MachineGunnur/GOG-Games#365]
Public funds and my programmes are used.

You do not pay a penny for hosting the site itself, people do, the donators that you shall respect while living for free; You use my applications and scripts to run the site, I have the full right to say outloud anything related to the site that I partly own and running as such. Either serve the people properly, respect the hand that feeds you or use no public funds and remove my code, only without the 2 you have the right to do, quote, "Whatever I want." 

As long as you use the public funds and my code, I am with you, up to the year of 2083 or a bit further, in your case that's forever, thanks for me being a Gen Z person. I likely might be the one who will run GOG Games after your death, generally speaking, and I can run on my own without anybody's money. In total, the point is: Don't bite the hand.

**Comment by Masamune3210** [comment]
Jeezus christ dude, chill the heck out

**Comment by undeadlet** [comment]
No dude here, [Masamune3210](https://github.com/Masamune3210). Why don't you say that to MachineGunnur rudely closing the issues and locking afterwards like a jerk? Isn't it bad to take the public money and claim yourself not responsible to the public's interests? Am I supposed to keep silent against the one who DMCA-attacked Torrminatorr? Bad, bad, no.

**Comment by undeadlet** [comment]
MachineGunnur responses to any issue one-sudedly and then closing/locking, that's the behaviour of an asshole.

**Comment by undeadlet** [comment]
You cannot imagine what the awful experience that was to sit on a Tox chat channel with MachineGunnur and listening to constant whining about Torrminatorr with trying harm the forum by all methods. This entity does not stand for pirate ideals and very selfishly greedy.

**Comment by undeadlet** [comment]
Put your eyes and the effort in keeping this asshole in check instead.

**Comment by undeadlet** [comment]
Like really, do keep MachineGunnur in check. Period.

**Comment by Masamune3210** [comment]
All I have seen is you acting like a scardy arsehat, its his repo he can do what he wants.

**Comment by Clickey** [comment]
To the Github repo, not to the site that's hosted by the public and uses my scripts underneath.

**Comment by Clickey** [comment]
Acting like "arsehat" is to "answer" to an issue and then lock it like MachineGunnur always rudely does or even deletes the issues.

**Comment by Clickey** [comment]
You would be correct if MachineGunnur haven't used my scripts and especially public money. If MachineGunnur will remove the 2, then yes, yes.

Like if I were hosting that abomination, which I don't see makes sense right now while all alive (the world has no need for ×2), I will use zero public money and only my own scripts, so I could say I can do whatever because zero public reliance. The pages are to be static for security reasons, and I don't think to use this repo, likely may build pages by a script; The site's hosting is very cheap and can use my existing foreign web server, the uploading and refreshing from my at-home RAID-1 2×16 TB server; ZippyShare prevented from expiring by a spider crawler.

I remember how Good Old Downloads died, so I keep a copy of everything.

**Comment by Clickey** [comment]
Frankly all what I have seen of you is being MachineGunnur's puppy.
