### ISSUE TITLE
Spellforce 3 Fallen God

### ISSUE THREAD

**Issue by hellwalker31** [MachineGunnur/GOG-Games#400]
While hate to open a issue, wanna say there is no way I can download this game or vote for a re-upload for this game. all links are done for, including torrent. Only fichier is able but cant download anything from  there. Even goodbyedpi or vpn is no solution. Country blocked it for real good. So I would like to ask about a re-upload of this game which was uploaded over 1 or 2 months ago at latest. Wouldnt open an issue if i had any other way.

**Comment by heaveneer** [comment]
There is! Swiss "ProtonVPN." The Netherlands, the US and Japan is free. I use it, I am broke.

While I agree on your point that the voting limit is counterproductive and should be, like, 29 days, I strongly disagree on the saying it is not availible because it is availible. At least on: Zippyshare, Send CM,  Pixeldrain, and 1fichier. I will say the statement it is not availible is not withstanding scrutiny, so please don't create issues like this.

**Comment by heaveneer** [comment]
By the way, it occurs to me you are from Russia: It does block 1fichier. So I do understand you sitiation veey well. I say confidently, ProtonVPN works great, no issues. Please do make use of it.

**Comment by heaveneer** [comment]
And honestly look into relocation. Like, Russia is shit these days, it has no future, we both know it, isn't so? Start from here:
https://t.me/GeorgiaRelocated

This is the real long-term solution.

**Comment by hellwalker31** [comment]
It passed 29 days and still no reupload button

**Comment by heaveneer** [comment]
[Read the FAQ](https://gog-games.com/faq), it's 60 days. 29 is what I wish it was, the expiration range is 30 on most servers. I gave you the way, it absolutely works, ZippyShare, etc is alive.

**Comment by heaveneer** [comment]
You must realize I am literally in your very country. When I claim it works via this VPN, it does so.

What I see is you totally ignore ZippyShare/etc which works in the country and decide not using 1fichier via the VPN. Please do use the VPN and don't forget to use the VPN's DNS. I physically use it on the daily on the router level, you will have no issues if this is set the same way properly. I, for the life of me, don't see it unavailible, otherwise I could emphatize with this and support the end target.

**Comment by heaveneer** [comment]
All the further is for MachineGunnur to decide. I've made my point, I see no meaning in updating what in reality has no issues.

**Comment by heaveneer** [comment]
Alive:
![Screenshot_20220519-140319_Fennec](https://user-images.githubusercontent.com/105858628/169312394-26ba50ee-e089-4b48-afac-7f92a63f2263.jpg)

**Comment by heaveneer** [comment]
Use this torrent, it has 2 seeders:
magnet:?xt=urn:btih:2ed7b7d86a8e72d07c37b75bb5a67310585f24f0&dn=SpellForce.3.Soul.Harvest.v161554.339115a-GOG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2990&tr=udp%3A%2F%2F9.rarbg.to%3A2830&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15760&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12750

**Comment by heaveneer** [comment]
And you know, no more silly OK.

**Comment by hellwalker31** [comment]
Tried proton also. No good. It even doesnt give 0.1 byte/s speed for free user. Uptobox, zippy, pixel are all dead, torrent is also dead. While Send.cm is  too slow and only 20 links are alive. Fichier is the only one alive but fichier is really blocked by dpi means. Just need a re-upload that's all.

**Comment by MachineGunnur** [comment]
Zippyshare - FINE
Pixeldrain - FINE
1fichier - FINE

Invest in a cheap VPN or something. Like PIA or Mullvad (preferred).
