### ISSUE TITLE
SUG: Date and background

### ISSUE THREAD

**Issue by coreyemtp** [MachineGunnur/GOG-Games#404]
First, thanks again for all the effort put into the site. It's an amazing resource! I have a couple suggestions:
1. Make the background adhere to the windows theme (e.g. dark theme), or provide a dark theme option switch
2.  Instead of showing the age as "7 days" or "1 year", simply show the year-month-day of the last update.
Very minor things, but would be helpful I think.

**Comment by unlockier** [comment]
These are not bugs, but feature requests! Both can be instaresolved locally by a user themselves in some way. 

1. Use Dark Reader with a few own aftercustomizations: [For Chrome](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh), [For Firefox](https://addons.mozilla.org/en-US/firefox/addon/darkreader/).
2. Subscribe to [RSS](https://gog-games.com/rss) to get what you want from, all RSS updates are always timestamped by date & time.

**Comment by unlockier** [comment]
The 1st, despite technically possible detection of the system-wide theme [by CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), is tricky because the backgrounds are provided by GOG itself and are bright by design. The new Galaxy-style, not brightedited, are not available for all the items. Of course CSS maybe can "offset" it, yet even in GIMP no result looked alright or I am not good at. It feels like too much of a headache for too little.

The 2nd is more realistic, I support that actually, it may somewhat help users updated on a particular date that do it less than weekly and are remembering only the date but for some unknown reason don't use RSS. Though, I must say, the users really should use it if need precise dates.

**Comment by unlockier** [comment]
Regardless, my words cost nothing. MachineGunnur likely will:
1. Close and lock the issue.
2. Say "simple no."

I don't expect "yes," I interacted with MachineGunnur for too long to certainly say that class of issues most of the time will face rejection. Nobody will put you on the bavk and say "thank you, good ideas, will try to do as soon as possible," etc. It's a given to be pessimistic in that environment. Sorry.

**Comment by unlockier** [comment]
*pat on the back

**Comment by unlockier** [comment]
Excuse me if that's too much to process. I am here from the very foundation day of GG.

**Comment by MachineGunnur** [comment]
Hey, thanks. I am working on a new and improved site. I won't add any features to the current one, but I will consider this for the new one.

Thank you!
