### ISSUE TITLE
broken line crashing

### ISSUE THREAD

**Issue by armygamer12** [MachineGunnur/GOG-Games#405]
every time I start the games it crashes on the title screen

**Comment by unlockier** [comment]
This is not a post-install GOG support channel.

**Comment by unlockier** [comment]
The reviews/forums have no widespread records on that, the installer is years old. This indicates a unique system problem, not a GG problem. Please stop thinking it is your personal support channel. 

The information you provided, the lack of, is insufficient to make a decision of the culprit even if I bizarrely wanted to. No error info, no OS, no S.M.A.R.T., no logs, no other meta given. From all I know it can be related to drivers, the GOG forum has a record of some crash on Intel/nVidia combo when the game chose Intel. Too many unknown factors to say for sure what causes it.

All what I ask is please make this class of issues on GOG's forum or any other forum related to technical issues. This place is not intended for it. When forums full of records of a broken installer (verification fails) or having an installer that installs a game that doesn't run on any PC because it's corrupt, only then tell. Any game not running on some Windows 666 John Doe Edition is not for here.

**Comment by MachineGunnur** [comment]
only supply the games, i cant fix game issues. go bug GOG.com or the devs ^^
