### ISSUE TITLE
Upload Reduction

### ISSUE THREAD

**Issue by gahrensc** [MachineGunnur/GOG-Games#42]
Hi, I know that you are reupload games quite often, and I thought it would be helpful if I mention you could save bandwidth cost by simply duplicating the files in drive and only sharing link of a copied file using Drive API. Rather than uploading again when link breaks, you can just copy a backup file in Drive and share new link. Might this help you save bandwidth cost and possibly be able to offer more platforms such as Linux? Kind regards, understandable if you cannot offer.

**Comment by MachineGunnur** [comment]
There are 2 issues - 
1. monthly bandwidth 
2. disk space

you solution solves 1. but not 2. 

the way people are acting now because they do not want to make a fake google, do a few clicks, copy to own drive makes me not want to work on project anymore. people never help, only complain. 

sorry for rant.

thanks for the input though and NOT complaining.
