### ISSUE TITLE
Help needed creating secondary google account

### ISSUE THREAD

**Issue by fopsc** [MachineGunnur/GOG-Games#43]
Hello,

So I'm having trouble creating a secondary google account, because google demands a phone number, and obviously I'm not going to identify myself with my real number, so I was using these free online sms services.

Most of the numbers don't work, but even when they do, google will lock your new account 2 days later, so any suggestions are welcome.

I'd like to try the workaround, but it's not super important, because I can wait a couple of hours until the daily limit clears.

@MachineGunnur 
On the subject of changing the file host: I think that you did a great job, gdrive is clearly superior to zippyshare and even if you can't download because of the limits, you only need to wait like 12 hours and jdownloader will auto retry and download any file once available.

You just need to understand that most people think that they won't be able to download ever again, that's why they are "angry".

Also, the person who said that absolutely no one in europe can access zippyshare was an ignorant fool, because it's only the UK, Germany and Spain:
https://techiestechguide.com/solved-zippyshare-403-forbidden/

So anyways, Big Thank You for your hard work, please don't abandon us!

**Comment by grenhunterz** [comment]
Try creating another account on a public wifi (without a VPN). It worked for me 2 weeks ago and they haven't locked my new account yet

**Comment by galneon** [comment]
Apologies to fopsc and MG for abusing the issues system, but I didn't know how to contact MachineGunnur otherwise:

I think it would help on the donations front if you had a home thread somewhere, such as on RIN. People felt more attachment to GOD, I think, in part because the crew were active and reachable via a prominent thread on RIN.

The dumb newbs bitching about the temporary Drive errors will never stop--GOD posted many notices about it. It's not going to get much better. You just need to write them off. If you can't ignore them and it's stressing you out day after day, then you have to do what will make you happy.

Thank you for your efforts! A little wait for the Drive links means nothing with JD2.

**Comment by AlolanMeowth** [comment]
Have made mine without a phone, an Android emulator, but no go now

**Comment by AlolanMeowth** [comment]
Have made mine without a number, an Android emu, but no go now

**Comment by gahrensc** [comment]
Thanks lots MG. We all love your work. Don't let the spam and invalid complaints get to you.

**Comment by AlolanMeowth** [comment]
The warning makes me write! "do not want to make a fake google:" Firstly, not all countries have a phone number without an ID; Secondly, today is literally impossible to avoid a number when making Google; Thirdly it allows like two dozens GB per day, it's nightmarishly slow on huge downloads compared to Zippyshare because of this data cups everywhere. "if don't like site, don't use or adapt:" I was a fan of but now this is slow to use or update some of my data then was before, so use much less or not at all. "Source code published:" But not all data.

"just need game:" Exactly the toughest part. In addition to have like 10 TB or so who are constantly growing is not an easy task, not to mention to efficiently maintain this. Wait, "demand for more and more?"... What? More??? For the way to work as it was is not more, it is the same. For me it almost never works unfortunately, only for a while no limits and then everything is off. "not one has donated any bitcoin," well, after, "people rarely help, only complain" and "makes me not want to work on project" makes me very unsure about the very site.

Again, the history: GOD have had a lot of choices instead of just Google or only Zippyshare. Its donations are mystery of history. merks213 has tonnes of items on P2P; has 1,886 likes on Torrminatorr, has own the thread "[Info] Good Old Downloads - A legend and its legacy" on RIN: mercs213 joined Torrminatorr in 2016 and made 402 posts, RIN in 2011 and made 2,184 posts. But u/MachineGunnur1965 on Reddit who is not currently active, the last message was 3 months ago and so empty: Nothing except Github, Reddit & Tox who's honestly pretty buggy at times.

You know, the only account that has been made by on a forum was misused and I have witness the event until its unlucky end, the second was purged (Was its avatar from an album of Disturbed by the way?). Let me say for a few days, I have witnessed an obsession with the forum, it didn't pass away. Do remember the rest and why I've to quit Tox. Google is not a significant issue with the "copy" workaround but makes everything slow and getting needed much slower at times when a thing is too big. No one was forcing to purge the old, could be kept, no updates.

Generally speaking: Want to go, go! I can only imagine how hard is to maintain but from like 30% offline of such, can't call too easy to do, especially alone. mercs213 was not alone, there is TwelveCharzzz and others to help: Donations were PayPal and Crypto, allows donate accounts, however no way to know its amount if any. A famous web site has 135 donations who begun from 2017, one each 5 days or so, $4,777.02 Total or $200 per month: Millions of users but the main source of its income is not donations, it's ads. If so much need money, why not ads?

Don't understand me wrong, I like GOG Games and many things were done smart but reading a long "warning" (in red and partially purple) who could be okay on the forum but looks like not belong there on a pretty minimalistic site is unusual for me. Perhaps, is it even helpful to complain about complains? Try to outsource some stuff if won't talk to people yourself. If no one to trust, sadly seems to be the case, if do everything alone, well, it is expected solely because the amount of work is great. Just imagine, the Entire GOG is in. The Entire Thing!

Unusual makes unusual. I am very sorry for such a long message but no other way. Reddit, no answers, ever; Tox is in my opinion inconvenient; but Github is Effective. If you do for money: Go Nuts, Do Ads! If not, try outsource. At the end of the day nothing is free. For example "free" parking lots are damn expensive to maintain. My point and possibly the point of other people is "do not want to make a fake google" not the case for too many people and no way to make it without a phone: This is not "want," this is no anonymity. How to make it privately?

What is the point of Github? Warnings about bugs and issues according to the FAQ. Currently Google Drive have become an issue. Github serves it's purpose. I have found "interesting" to read "There are no plans at this time to add or use others" when I remember how fast and rushed out Google was, implemented for the reason to have less complains but ironically seems only increase the flood. "If come here to complain about Google Drive, please leave. Not helpful" doesn't work as the topic where you're reading exist. People are worry, "please don't abandon us!"

I have mixed feelings about "galneon." On one hand they're right, on another kinda wrong. The Bright Side is: GOG Games is a lot of work, good work, donate is a great idea. The Dark Side: If the donation will be made after threats, it can root in such behaviour, could expect more threats and possibly worse, in my opinion this is not acceptable. "gahrensc," the complains are "valid" from an experienced user standpoint, understandable, as understandable the response, but to call such messages "spam..." it isn't "spam," an issue: It worked before fully.

I expected everything to be calm: No point of me spending any time on Tox, talking about Climate Change and other stuff, chat out about the particular forum or some applications. Was I wrong? Yes, after the free Google account, no calm. The only reason I am here is because the red warning provokes. I found incredibly useful to name my folders with slug and use it to easily compare data to know if everything to update (the site has filenames), occasionally I tend to go on some sites and just to know how GOG Games goes, do read Github's issues, so I'm here.

Issues? "Shovel Knight: Specter of Torment" is missing but technically included in its Treasure Trove. Duke Nukem games could be updated, as some Doom, however, not too much of a difference I guess anyway. Is it worth creating an issue? I don't think so. I am reading the "Change file hoster," emmm... "shakeyourbunny" is right, it was downgrade compared to, sorry. "vujaja" was misleading, only 3 countries, 196 and not 741 Million. hellwalker31's Cloud Mail.ru is worse, bad speeds, also call 700 Million "bad" 'cause of one is at its "best" questionable.

Most of the time people do stuff from the best intentions. Yes, "gahrensc," everything is avoidable and those complains are trash if you know what to do anyway, as goes my message. Yes, "MachineGunnur," it was made with good in mind, I understand why the change was made, thought about non existing 741 Million. Those 3 Countries easily can use ProtonVPN or another free proxy and no issues. If follow "adapt," could not listen to "change the hoster:" They should adapt, not you, isn't it? "hellwalker31," well, maybe from your experience it makes sense...

Can made this turn: Mix out. At first use Zippyshare, if reupload once, still Zippyshare, if twice, Zippyshare but if three times, Google Drive because it shows the file is very unpopular. This way no increase with traffic and everyone should be happy: A compromise! However, my suggestion should be met with Caution: I don't share everything and only download from time to time. Interesting: Is it possible to use Google Drive for own downloads/uploads and cut the cost of HDDs? Use Google Drive as an HDD, download temporarily, upload to Zippyshare when needed. Mmm?

P.S. I will very likely delete the message after a few days but please delete it yourself if did read, I dislike my message. Thanks!

**Comment by galneon** [comment]
Please don't post yet again, Alolan Meowth. You're doing more damage. Thanks.

**Comment by MachineGunnur** [comment]
thanks, for issue try internet on phone by carrier, maybe? public wifi also good suggest!

**Comment by AlolanMeowth** [comment]
I'm Meowth, not a kitty. What the damage? P2P's no damage. Don't understand

**Comment by galneon** [comment]
I was referring to the long rant you ended with:

"P.S. I will very likely delete the message after a few days but please delete it yourself if did read, I dislike my message. Thanks!"

and other posts you've quickly deleted. Yes, they're delivered in full via email notifications. Let's not waste more of MG's time.

**Comment by AlolanMeowth** [comment]
Hah. You do realize, MachineGunnur likely doesn't read or get those? My fault, forgot about notifications. Mistaken, I deleted my own message, understand? I have to rethink. After that I checked out the post and see here your spam with my name. Please delete this yourself, it is totally offtopic and has nothing to do with Google, therefore it goes against your own target of not wasting time since it creates meaningless conversations who don't bring anything useful. If you're following your own words, you know what to do rightfully. You need to understand that in the current context and for anyone who don't use eMail it looks like you're complaining about my P2P post.

Also I still think to give "good" to a person who making threats can backfire. I remember a conversation with the person where it was suggested to make a threat of closing to force people to pay by MG themself: I don't support it, it is a bad habit. If you are, indeed, standing for the best, could don't give anything in current circumstances at least. Now the mistake has been made, I expect more threats, the person's behavior was given a shot into the wrong way. Also, sorry, "rant?!" galneon, maybe it was not exactly the right word? Definition: "to talk loudly and in a way that shows anger, to complain in a way that is unreasonable." This sounds strange if to read the message itself.

To have this conversation in the first place is rantly: The conversation is unreasonable to anyone who don't receive eMails. My reasoning of writing was mainly reading this terribly long red warning on GG who is clearly "rant." You know it, aren't you? However, I thought that if MachineGunnur experiencing misunderstandings with English very frequently, the consequences of Mistranslation from Russian or whatever language the person uses are too high and I don't want to take Full Responsibility for that, so I deleted it yourself. Unfortunately someone called galneon has taken it in its face value and thought it was MG deleted it when it is not. So calm down and go off!!!

**Comment by AlolanMeowth** [comment]
LET'S NOT WASTE OUR TIME FOR.

**Comment by Myuutsuu** [comment]
...galneon, you're so annoying.

**Comment by SkinDread** [comment]
Funny. You're the only negative part in this thread. Wipe out yourself!

**Comment by SkinDread** [comment]
Also, sorry, "him?" Are you kidding? My gender is female, Freak. x)

**Comment by fopsc** [comment]
thanks for the account creation suggestions, will try them out!

**Comment by fopsc** [comment]
oh, btw does anybody know:
if I manage to create an account and then get a cheap ebay team drive assigned to it,
would I be able to copy the GOD shared files directly to the team drive?

**Comment by MachineGunnur** [comment]
i think the Make copy goes to your personal drive - you need business one instead. ~10 € month

**Comment by fopsc** [comment]
thanks everyone i'll close this issue now!
