### ISSUE TITLE
Something wrong with Multiup links !!!

### ISSUE THREAD

**Issue by tomgates** [MachineGunnur/GOG-Games#95]
Something wrong with Multiup links !!!
after the "download" button on the Multiup site, It showed many mirror clouds for choices.
But it can't be download, it just redirects you to "multinews  website" or somewhere.

**Comment by guedela** [comment]
Same! Strange though, a few weeks ago did work. Why??? Hope Multiup can fix it, it redirects me, too, gives no file; I'm on latest Firefox on Tor with uBlock. Meanwhile Zippyshare works just fine.

**Comment by MachineGunnur** [comment]
go write to MU. its their issue. I just did. we have wait and see now.

**Comment by MachineGunnur** [comment]
OK, looked at more very quickly. 

Whatever change was intentional by MU team. I tried without adblocker stuff on a few browsers and still had issues.... BUT When I tried Edge, finally got the fucking download links! Of course JD2 is broken to. 

If JD2 team doesn't fix soon, I'll look into another mirroring service.

**Comment by MachineGunnur** [comment]
using Mirrored.to now. closing.

**Comment by Vihakijo** [comment]
Thanks!

**Comment by tomgates** [comment]
thanks !!!

**Comment by MachineGunnur** [comment]
@tomgates  FYI - JD2 is again working here with multiup.org. seems mirrored.to has a daily 500 api limit call >_> so unless we can get that fixed just going back to MU
