### ISSUE TITLE
To Catch The Rare Upload Bug

### ISSUE THREAD

**Issue by ghost** [MachineGunnur/GOG-Games#96]
Deeply sorry for remaking the issue but @Guessol is flagged, no idea. [GOG Tests](https://gitlab.com/mjr-awesome/gog-tests) can find the rare bug if exists. Run with no options, will check all from RSS. This is how the 3 were found (House Flipper, etc). Not perfect but works.

**Comment by Vihakijo** [comment]
Now with Mirrored, too.

**Comment by MachineGunnur** [comment]
Link me the game, on the site, which has missing parts.

**Comment by GhostAwesome** [comment]
New? Currently have 2 out of 2,539 but they are too old. I added an option for you to test all site links at once by "-a." Only can do so far. Well, if asked, the 2:
https://goggamespc7v6z5e.onion.ws/game/1126406171
https://goggamespc7v6z5e.onion.ws/game/1140907376

**Comment by MachineGunnur** [comment]
yea, those were before logging was turned on and before increase of cURL retry limit. need more recent uploaded game, so if you ever find. post here.

**Comment by GhostAwesome** [comment]
Yes. May the limit helped? I don't test often, honestly, mostly only my very few games when autoupdating once in a blue moon. This is why I published the code! You're updating highly frequently, can please set test at the end, simply? It'll be Ideal.

Today the last time I tested Railway Empire and all latest from RSS for you: Nothing.The chance to met was 00,15% before the increase, now less.

The script does what I could do but better. I'm not needed anymore. Will be less active in upcoming months (work, life, friends, etc), no time, can't help further than it is, excuse me. Run it, will have me in a sense. Why do you need me phisically for running the script? No way. If a problem with the script, though, make an issue, will try to check Git once a week.

You have an easy way to catch, so, Good Luck!

**Comment by MachineGunnur** [comment]
i have yet to view your code i'll take look at it and see if i can integrate.

the upload script is set to infinitely upload each part and only BREAKS the infinite loop until the output url matches *file.html* for zippy and *download* for MU. if not, it will retry endlessly.

the only way it can fail is if the cURL retry limit is reached.

**Comment by tomgates** [comment]
game-cooking simulator.part05.rar in google driver missing 
game-railway empire/.ay_empire.part20.rar in google driver missing

**Comment by MachineGunnur** [comment]
@ tomgates  MU fails sometimes. can't help it....

**Comment by tomgates** [comment]
@MachineGunnur.  Got it.  Thanks.

**Comment by GhostAwesome** [comment]
Big Thanks and my Highest Appriciation for the description! Well, by all means it shouldn't happen, however, you know.

Let me describe my script ([PrivateBin](https://bin.privacytools.io/?b5dba7c2d2704e98#6bW0gQzOzRQe2cSXQXxjGjmG+ok00hUKjgCNQ+rOBVw=)), too. I am not using comments in code, might be necessary, I feel obligated in a sense. Won't tell beyond the code, even thought I really want to.

At the beginning checks if Curl is present or Tor is running, if not, no web tests, only SHA-1 Verification.

The gg_sum function (-c):
1. The Verification parses [DAT from Connie](https://onedrive.live.com/?authkey=%21APgbl3v0s41kQUQ&id=201ECFA3DD196829%2121848&cid=201ECFA3DD196829), else want an already parsed sha1sum who is a compilation of 17 GOG DAT (supports 31,238 files).
2. Performs a file check and searches its SHA-1 in sha1sum, if catch, "OK," if finds a filename but no catch, "FAILED," otherwise "UNKNOWN."
3. Technically can be used to recover the name of a file 'cause shows a name from the sha1sum file instead of the current name in Output.

The gg_all functin (-a):
* Parses the "all" page to know the total number of pages and how much to parse, then takes all slugs from the site into a file in /tmp/, if a page fails, just exits, probably better would be set it into a loop but I need it this way for my own reasons, in any case if succeeds, runs the newly made file in Bash to take all by gg_test function, deletes the made file at the end.

The gg_test function (-t):
1. Checks if the user is sane or not nuts and a slug/ID is fine, loads the site's queue plus the game page, doesn't load more and loads only once, parses them to know if it is processing in Queue or soon will be, takes download links and counts how many (all, by types, etc) to use later.
2. Then performs tests on if the Queue Loaded, if the game is updating, if coming soon, just warns but warns only if "Upload has't started yet" on the page.isn't 1st in queue, afterwards checks if the game page was loaded, if an EXE is here at all, if has Zippyshare, it always expects Zippyshare.
3. If Multiup or Mirrored is present, compares the count of links against Zippyshare, if mismatch, then tells "Broken."
4. Sets Maximum Archive Counters to zero if a type (Game, Extras, Patch) doesn't exist, afterwards checks if the highest archive of each type combined matches the total amount of links to catch missing.
5. Additionally if a page claims to have a type but has no links for, in a case when only Zippyshare is used, it will expect at least one  link from and warn if there is none.
6. Finally, since so uncommon to have literally 500 MB as the last archive but past archives always are, checks if the last Zippyshare link of each type looks unusual and tells if that's the case and likely the last archve is missing.

After all the above, if passes tests, tells "are OK."

**Comment by MachineGunnur** [comment]
Nice write up thank you I'll play around with it today

**Comment by GhostAwesome** [comment]
Great to Hear! @ghost can't edit and I found, sadly, errors (108–118). Fix:
*2. Then performs tests on: If the Queue Loaded; if the game is updating; if coming soon, just warns, then tests but warns only if no "Upload has't started yet" on the page and isn't 1st in Queue, else throws "Error," exits. Afterwards checks if: The game page was loaded, if an EXE is here at all, if has Zippyshare; It always expects Zippyshare.*

"Coming" is the only "test" who doesn't exit because links are functional at next, it's like a Notice 'cause GOG Tests originally has been made to run before [Jani Yadi's Downloader](https://github.com/JuniYadi/zippyshare). After a rest I re-reread the post, re-read the code, looks fine; Ran, tested, if wrote "vb," said "Item Load Failed." But I badly forgot to show an error if $2 isn't set but $1 is "-t" as such it showed OK to nothing. Why? Didn't add "else"  for "if echo $slug | grep ." who is likely better to be "if [[ -n $slug ]]."

**Comment by MachineGunnur** [comment]
https://gitlab.com/mjr-awesome/gog-tests/issues/1

**Comment by GhostAwesome** [comment]
New v.1.0.3.9 has no `@Q` who worked on Bash 4.4+.

**Comment by MachineGunnur** [comment]
@ghostOK script works now! do you have way to communicate? i found an issue you can fix for improvement. better to chat quickly in real session.  thanks again.

**Comment by MachineGunnur** [comment]
nvm

**Comment by MachineGunnur** [comment]
OK, now implement the link check script. Run AFTER after ZS/MU upload done. If error happens, it writes to log file. Can check and fix when happens. Thanks. Neat script.

**Comment by rogue-cucumber** [comment]
Nice! Thus no need in the tests' repo itself, it's implemented. If someone else wanted the script for a strange reason, v.1.0.3.8 is on Bin but only for a month. The faith of the v.1.0.4.0 code is in your hands but probably better to be private. Thank you for the star, though! Won't be forgotten, ever.

On the bright side the script assures no one will ever bother you about a missing RAR here, you'll notice 1st hand without reading an issue. However need only one repo remain, personal reasons, unfortunately. In addition it isn't GOG Times who continues to be supported for the foreseeble future and needed for the public, especially since a lot of downloads were in 1999. As said, November and forward can't offer me much free time, but will try to check issues once in a while.

I think if Cloud change, should have no problem to replace an address or add new yourself, same to modifications of any kind at the tests. I'm certain the bug will be catched, sooner or later, and fixed thereafter.

Great to know as just a user. Thanks again! Take a star, too.
